dulwich/client.py

Currently hg-git push/pull to/from local git repo will fail if no git was installed, implemented this so hg-git can use LocalGitClient for local scheme instead of SubprocessGitClient

Implement LocalGitClient.send_pack

---

dulwich/objects.py
dulwich/tests/test_objects.py

The `self._needs_serialization` flag is not cleared properly inside `Tree._serialize`, `Commit._serialize` and `Tag._serialize`, which forces those objects to compute their SHA over and over again. It is actually sounds more logical to clear the flag directly inside `ShaFile.as_raw_chunks()`, which is responsible for calling `ShaFile._serialize()`.
There are no tests covering this that I can see, so I added some.

Most `ShaFile` objects don't cache their SHA properly

---

dulwich/client.py

This fixes a bug from a mistake I made. I'm not sure how I did not pick it up. I probably changed it and did not run the test, and the test dose not run on travis as it is windows only.

Fix test_client.TestGetTransportAndPath.test_local_abs_windows_path

---

appveyor.yml
dulwich/tests/compat/test_server.py
dulwich/tests/compat/test_web.py
setup.py

This adds an appveyor config file. To get it running, you (Jelmer) will need to create and account on appveyor (which is free of charge for FLOSS projects) and add a project for dulwich. 
This is what the output will look like: https://ci.appveyor.com/project/garyvdm/dulwich
This also disables some things that were preventing the tests from completing.  Fixes for these issues will still needed in the future.
In the future, we can use appveyor to build binaries for windows. (Issue 222)

Appveyor: Windows CI

---

dulwich/file.py
dulwich/hooks.py
dulwich/index.py
dulwich/object_store.py
dulwich/objects.py
dulwich/pack.py
dulwich/porcelain.py
dulwich/refs.py
dulwich/repo.py
dulwich/server.py
dulwich/tests/compat/server_utils.py
dulwich/tests/compat/test_pack.py
dulwich/tests/test_file.py
dulwich/tests/test_grafts.py
dulwich/tests/test_hooks.py
dulwich/tests/test_object_store.py
dulwich/tests/test_objects.py
dulwich/tests/test_pack.py
dulwich/tests/test_porcelain.py
dulwich/tests/test_refs.py
dulwich/tests/test_repository.py
dulwich/tests/utils.py

Fixes #263
For a number of user facing methods, make it possible to pass in paths in as either a unicode string, or bytes. These include:
* `Repo.__init__`
* `Repo.init`
* `Repo.init_bare`
* `index.build_index_from_tree`
* `index.get_unstaged_changes`
The repo.Repo.path attribute will remain unchanged. The Repo._controldir attribute and a new Repo._path_bytes attribute are ensured to be bytes.
For a number of internal methods, it now requires a bytes path rather than
a unicode string. These include:
* `objects.hex_to_filename`
* `objects.filename_to_hex`
* `_GitFile.__init__`
* `ShellHook.__init__` (and subclassed of ShellHook)
* `DiskObjectStore.__init__`
* `DiskRefsContainer.__init__`
* `Repo._put_named_file`
* `Repo.get_named_file`
* `pack.write_pack`
* `Pack.__init__`
* etc...
For the …

Change the way methods that take a path argument behave. 

---

NEWS
dulwich/client.py
dulwich/object_store.py
dulwich/porcelain.py
dulwich/repo.py
dulwich/tests/compat/test_client.py
dulwich/tests/compat/test_pack.py
dulwich/tests/compat/utils.py
dulwich/tests/test_client.py
dulwich/tests/test_index.py
dulwich/tests/test_object_store.py
dulwich/tests/test_porcelain.py
dulwich/tests/test_repository.py
dulwich/tests/utils.py

This PR is an alternative to PR #273. It dose not make ObjectStore and Repo object context managers. Rather it uses contextlib.closing.

Close Repo/ObjectStore/Pack objects alternative

---

dulwich/client.py
dulwich/file.py
dulwich/hooks.py
dulwich/index.py
dulwich/object_store.py
dulwich/objects.py
dulwich/pack.py
dulwich/porcelain.py
dulwich/refs.py
dulwich/repo.py
dulwich/server.py
dulwich/tests/compat/server_utils.py
dulwich/tests/compat/test_pack.py
dulwich/tests/test_file.py
dulwich/tests/test_grafts.py
dulwich/tests/test_hooks.py
dulwich/tests/test_object_store.py
dulwich/tests/test_objects.py
dulwich/tests/test_pack.py
dulwich/tests/test_porcelain.py
dulwich/tests/test_refs.py
dulwich/tests/test_repository.py
dulwich/tests/utils.py

I now think PR #271 was a mistake.
When I started looking a the test results on Windows Python 3 (https://ci.appveyor.com/project/garyvdm/dulwich/build/1.0.104/job/5j9b65x7phrex8tn) , I picked up an issues caused by that change:
As discussed in that PR, `open(bytes)` works fine, but if you do `os.stat(bytes)` or a bunch of other methods in `os`, you get:
DeprecationWarning: The Windows bytes API has been deprecated, use Unicode filenames instead
That's bad. Don't want to be using deprecated features.
This reverts that change.  So now for paths must be `basestring` on python 2 or `str` but not `bytes` on python3.  The tests in `test_repository` will test with a unicode path so that we don't regress on #263. 
This also has 2 minor fixes for windows related to path handling.
I think we still …

Revert byte paths

---

dulwich/tests/compat/server_utils.py
dulwich/tests/compat/test_client.py
dulwich/tests/compat/utils.py
dulwich/tests/test_blackbox.py
dulwich/tests/test_client.py
dulwich/tests/test_index.py
dulwich/tests/test_porcelain.py
dulwich/tests/test_refs.py
dulwich/tests/test_repository.py
dulwich/tests/test_server.py
dulwich/tests/utils.py

I noticed there are a lot of temp dirs not deleted when we run the test suite. This fixes them all.
Also, in a few places where we have 
try:
....
finally:
cleanup
change to just calling `self.addCleanup`

Make sure we clean up all temp dir when running tests.

---

dulwich/index.py

I think this was intended but forgotten.
Also, a doc string spelling fix.

In index.build_index_from_tree, pass the validate_path_element onto validate_path.

---

dulwich/tests/test_index.py
dulwich/tests/test_repository.py

I recently discovered that `os.symlink` & `os.readlink` are available on windows as of python 3.2.
So where we have tests that require symlink support, we should check if symlinks are available with ` hasattr(os, 'symlink')` rather than checking `sys.platform` or `os.name`. This enables running these tests on Windows with python >= 3.2.
This introduces a new test failure on Windows python 3, but this is fixed by #290. (https://ci.appveyor.com/project/garyvdm/dulwich/build/1.0.164/job/2u7ra0kyj3onass1#L1131)
This also fixes a test windows failure due to a difference `stat_val.st_size` between windows and unix (on unix 1 byte, on windows 0 bytes.)
This also splits up `BuildIndexTests.test_nonempty` so that the symlink specific code is in a separate test, so that the majority of …

Symlinks stuff

---

dulwich/client.py
dulwich/tests/compat/test_client.py
dulwich/tests/test_client.py

On windows python3, executable names (e.g. `args[0]`) must be a string and not bytes. 
This fixes these errors: https://ci.appveyor.com/project/garyvdm/dulwich/build/1.0.171/job/v2mohbox9v14yxyi#L1161

Fix SSHGitClient on windows python3

---

dulwich/tests/compat/test_client.py

For I number of reasons, I would like to get the test suite passing on appveyor. 
The error in `dulwich.tests.compat.test_client.DulwichTCPClientTest.test_fetch_pack_no_side_band_64k` is one of the last remaining issues to solve. I had a number of tries to solve it, but so far have failed to find out why it brakes. 
So patch marks this test as a expectedFailure on windows, and I will come back to it later.

Mark DulwichTCPClientTest.test_fetch_pack_no_side_band_64k as expectedFailure on windows.

---

.travis.yml
setup.py

Travis now allows you to run your in a docker container rather than in a VM. The main advantage is that the tests start running much sooner after a push, due to both a faster startup time for the container vs the vm, but also because the vm queues are often full. 
http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
https://www.traviscistatus.com/#month
The issue with this is that you can't use `apt-get` to install dependencies, because you can't use `sudo` in the container. If I understand correctly, the reason for using `apt-get` vs `pip` was for performance reasons (Installing gevent/geventhttpclient is quicker with `apt-get` than with `pip`.)
However `pip` gained a new feature in 7.0 (thanks to @rbtcollins) to build a binary wheel, and cache it. This …

Rework travis config so that it uses containers & pip caches

---

bin/dulwich
dulwich/client.py
dulwich/porcelain.py
dulwich/tests/compat/test_client.py
dulwich/tests/test_client.py

Includes an ls-remote porcelain command to demonstrate the new functionality.

Extend clients to support listing remote refs

---

dulwich/repo.py
dulwich/tests/test_repository.py

Method to instantiate a `Repo` object from a subdirectory of a repository (this is kind of normal Git CLI behaviour), they have it in the [Rust lib](https://github.com/alexcrichton/git2-rs/blob/master/src/repo.rs#L64-L74) so I "borrowed" it.

Add `discover` classmethod

---

dulwich/client.py
dulwich/tests/compat/test_client.py
dulwich/tests/test_client.py

gitolite, which restricts access to repositories through SSH without allowing "full" SSH access, uses the following regular expression to determine if a command is a "valid" git command:
```
if ( $soc =~ m(^($git_commands) '?/?(.*?)(?:\.git(\d)?)?'?$) )
```
https://github.com/sitaramc/gitolite/blob/24171564e63d4072b2eeeb3e4dad7d2b231b31ec/src/gitolite-shell#L156
This means that gitolite will only accept commands that have the repository path in single quotes (and nothing else). This pull request adds the single quotes around the repository path in SSHGitClient again.
Fixes #384.

Add single quotes around the path argument in SSH clients

---

dulwich/server.py

`UploadPackHandler` is for uploading a pack _to_ the client. Fix the class comment.

server: trivial comment fix

---

dulwich/tests/test_web.py
dulwich/web.py

This is a follow-up to 5a69c46 which misses the fact that even though an input stream might have 'seek' and 'tell' methods, they do not necessarily have to be implemented.  See also http://bugs.python.org/issue12877

Don't expect 'wsgi.input' to have working 'seek' method

---

dulwich/fastexport.py
dulwich/tests/test_fastexport.py

The `fastexport.GitFastExporter` generating invalid exports, like this one: 
```
$ > git fast-import << EOF
blob
mark :1
data 17
{"name": "Felix"}
commit refs/heads/master
mark :2
author Foo Bar <foo.bar@foo.bar> 1461062670 -0200
committer Foo Bar <foo.bar@foo.bar> 1461062670 -0200
data 14
Initial commit
M 644 1 test
EOF
$ > fatal: Invalid dataref: M 644 1 test
```
The line`M 644 1 test`  should be `M 644 :1 test` 
I fixed `fastexport.GitFastExporter._iter_files` method and the corresponding test.

fastexport module : Invalid dataref 

---

dulwich/config.py

Makes the behavior match ``git`` a bit more.
``git`` also supports ``GIT_CONFIG``, but it has a funky API whose semantics are changed by CLI args, and with the way this object works (``StackedConfig``) I don't see a decent way to support it.

Add support for $XDG_CONFIG_HOME/git/config and GIT_CONFIG_NOSYSTEM.

---

dulwich/objectspec.py
dulwich/porcelain.py
dulwich/tests/test_objectspec.py
dulwich/tests/test_porcelain.py

One in ref parsing, one in annotated tag times.
As discussed on IRC, the former still doesn't fix deleting tags from a remote repo, but I'll follow up on that after this.
Thanks!

Fix two typos

---

dulwich/client.py
dulwich/porcelain.py
dulwich/tests/test_client.py

Adds get_url()-method for getting nice looking urls from clients. This url can be used for example for log or debug messages. 
This pull request is in preparation for adding support for http-authentication where username and password are in url and should not  be written to log.

Add get_url()-method to clients

---

appveyor.yml

- Added PY3.5 (32 & 64 bit).
- Upgraded *win32* lib from [build-219(2014) --> build-220(2016)](https://sourceforge.net/projects/pywin32/files/pywin32/).
- The success ratio has not changed (neither with the new *win32* lib nor under PY35):
- [2014-win32 (build-219)](https://ci.appveyor.com/project/ankostis/dulwich/build/1.0.2):
- PY27-32bit: (failures=1, skipped=147, expected failures=1)
- PY34-32bit: (errors=25, skipped=153, expected failures=1)
- PY35-32bit: (errors=25, skipped=153, expected failures=1)
- PY27-64bit: (failures=1, skipped=147, expected failures=1)
- PY34-64bit: (errors=25, skipped=153, expected failures=1)
- PY35-64bit: (errors=25, skipped=153, expected failures=1)
- [2016-win32 (build-220)](https://ci.appveyor.com/project/ankostis/dulwich/build/1.0.3):
- PY27-32bit: …

appveyor: upgrade win32 to build-220, add py3.5

---

NEWS
dulwich/porcelain.py
dulwich/tests/test_porcelain.py

Spotted a bug, wrote test-case for it, fixed the bug.
This is just a prelude to fixing a more elaborate issue, which is that porcelain.reset() will leave files in the working directory that should be removed when doing a hard reset.

Fix porcelain.reset to not ignore committish argument.

---

dulwich/tests/test_walk.py
dulwich/walk.py

Add a path_prefix argument to WalkEntry.changes() to let it compute only
the differences under a portion of the tree represented by the change.
This is slightly different than the paths argument to Repo.get_walker()
because it allows the Walker to produce WalkEntry objects for which
there are no changes under the path, and then realize that as the
calling code iterates over the results. This is useful in cases where
the caller needs to have access to all commits (for example, to see
where tags fall), but may only care about some actual file changes under
a portion of the repository.
Signed-off-by: Doug Hellmann <doug@doughellmann.com>

add path filtering to WalkEntry.changes()

---

NEWS
dulwich/repo.py
dulwich/tests/compat/test_client.py
dulwich/tests/test_client.py
dulwich/tests/test_index.py
dulwich/tests/test_porcelain.py
dulwich/tests/test_repository.py

This makes Repo a context manager to allow closing using `with` (like most other closable dulwich classes).
As demonstrated by the test suite changes, this can dramatically simplify some uses. :)

Repo: enable "with" statement support for closing

---

dulwich/client.py
dulwich/tests/test_client.py

Proposed fix for the bug: https://github.com/jelmer/dulwich/issues/475

Unquoting credentials before passing them over to urllib2

---

.travis.yml

My initial intention was to add 3.3 and see what failed, and I realized half-way that it was already there. 😛 
Anyway, this cleans up task definitions a bit to dedupe quite a bit. Also add pypy3 to the test matrix.

Travis tidy up

---

dulwich/client.py
dulwich/tests/test_client.py

``path`` is supposed to be a bytestring according to [here](https://github.com/jelmer/dulwich/blob/master/dulwich/client.py#L1168) and [there](https://github.com/jelmer/dulwich/blob/master/dulwich/client.py#L1181), while ``self._base_url`` is a ``str``, that will result in ``TypeError: Cannot mix str and non-str arguments`` when calling ``urlparse.urljoin``.

Fix TypeError: mix str and non-str arguments

---

dulwich/ignore.py

This happens for example on Windows.

ignore: Fix default_user_ignore_filter_path when HOME is not set

---

dulwich/ignore.py

We might want to convert all paths to POSIX to make this work with platform specific paths (Windows paths 😛) See https://github.com/jelmer/dulwich/issues/526#issuecomment-315002252.

Don't use os.path.sep since that changes with the platform

---

dulwich/hooks.py
dulwich/tests/test_hooks.py

this makes the behaviour of dulwich more similar to CLI git, while keeping flexibility for custom dulwich hooks/apps. 
see https://github.com/jelmer/xandikos/issues/65

improve hook compatibility by setting cwd

---

dulwich/porcelain.py

The 'origin' parameter in porcelain.clone() wasn't being fully properly
used, as the actual remote was still being set to the default name of
'origin'.  Make the code use the paramter instead at the proper places.

Properly use origin parameter in porcelain.clone() (Issue #565)

---

NEWS
dulwich/objects.py
dulwich/tests/test_objects.py

Here is my take on #567.
Cheers,

Add some more checks on commit/tag

---

dulwich/config.py
dulwich/tests/test_config.py

The current code looks for a `-1` return value from the `string.index` method (as e.g. `string.find` yields), but `string.index` will raise a `ValueError` if the character is not found, breaking out of the block before being able to check the value.
Catch the `ValueError` from `string.index` and raise a new one with the intended exception message instead.
Added a test for incorrectly formatted section headers that should trigger this exception as well (somewhat related to #579).
(I tried to keep with the surrounding code style even though [the contribution guide](https://github.com/jelmer/dulwich/blob/master/CONTRIBUTING.md) preferred `'` as string delimiter.)

Make unreachable `raise ValueError` come into play

---

dulwich/archive.py
dulwich/tests/test_archive.py
dulwich/tests/test_client.py

I noticed in #579 that code style checks fail CI builds after 64e084e77d1e833455a89d5ac1ff482782e28096. This should fix that, as well as remove a deprecation warning when running unit tests by changing a `self.assertEquals` to `self.assertEqual`.

Lint fixes

---

NEWS
dulwich/config.py
dulwich/tests/test_config.py

Comment characters (`#` , `;`) that are within balanced quotes should not discard the rest of the line:
[branch "my#branch"]
is a valid section for a branch named `my#branch` ([`#` is a valid character in a branch name](https://git-scm.com/docs/git-check-ref-format)). Previously this normalized to:
[branch "my
which raised an exception for finding an invalid section header.
Adhering strictly to the exact allowed comment format might require more care, but this should at least fix some problems I have had with real-life repositories.
(I tried to keep with the surrounding code style even though [the contribution guide](https://github.com/jelmer/dulwich/blob/master/CONTRIBUTING.md) preferred `'` as string delimiter.)

Improve handling of comment characters in Git configuration files

---

dulwich/config.py
dulwich/tests/test_config.py

This is done to match the behaviour of git itself.
The main change here is to add the lower_key function and the CaseInsensitiveDict class.
lower_key coerces keys that are used in DictConfig to make sure all keys consist only of lower-cased strings.
CaseInsensitiveDict has altered __getitem__ and __setitem__ methods to call lower_key on the key for both get and set operations.
CaseInsensitiveDict.make takes care of the creation logic found in ConfigDict.__init__ as well as converting any passed-in dicts to CaseInsensitiveDict.
CaseInsensitiveDict.get and CaseInsensitiveDict.setdefault allow the default value returned to be a CaseInsensitiveDict without repeating it everywhere.
ConfigDict.check_section_and_name just moves some logic that was previously repeated.
Fixes #599

Make config keys (sections and names) case insensitive

---

dulwich/fastexport.py

For some reason the code was moved around and refactored and there was a regression for the handling of markers in commit commands. This restores the behavior I initially introduced in a2edfbf9f1f31850589fcb9a10df89089d6a030b .

fastexport: restore handling of markers in commit commands

---

dulwich/porcelain.py
dulwich/refs.py
dulwich/tests/test_porcelain.py
dulwich/tests/test_refs.py

The previous version of porcelain.fetch() simply returned the remotes, but didn't update the on-disk information.  This should correct it.

Make porcelain.fetch() actually do the fetch into the local checkout

---

NEWS
dulwich/client.py
dulwich/contrib/paramiko_vendor.py
dulwich/tests/compat/test_client.py
dulwich/tests/test_client.py

Update for `SSHVendor`, `SubprocessSSHVendor`, `SSHGitClient` and `ParamikoSSHVendor` classes:
`SubprocessSSHVendor` now use `putty.exe` on `win32` platform and `sshpass` or `ssh` on other depend on the options.
`ParamikoSSHVendor` class currently most useful and can use all `paramiko.client.connect` options, but this options should be given on `__init__` call or with `run_command`. Also `SSHGitClient` can't pass this options except new `password` or `key_filename`

Add ability to use password and keyfile ssh options

---

NEWS
dulwich/client.py
dulwich/tests/test_client.py

The PLinkSSHVendor uses the [command-line tool `plink`](https://www.ssh.com/ssh/putty/putty-manuals/0.68/Chapter7.html) instead of `putty` to make SSH connections.

Add a new SSHVendor to allow plink use for SSH connections.

---

NEWS
dulwich/porcelain.py
dulwich/tests/test_porcelain.py

In #614, `porcelain.fetch` was changed to write the updated local knowledge of the remote state to the repo, in a similar way as how it is done in `porcelain.clone`.
However, the implementation in `porcelain.fetch` did not strip the `refs/heads/` prefix on the remote refs before prefixing them with `refs/remotes/<remote_name>/`, which meant locally creating refs such as
.git/refs/remotes/origin/refs/heads/master
instead of the correct form
.git/refs/remotes/origin/master
This pull request addresses this by replacing the logic in `porcelain.fetch` with the one already present in `porcelain.clone`, and removing it entirely from `porcelain.clone` by letting it issue a call to `porcelain.fetch` instead.
An assertion is added to the `porcelain.fetch` tests to check that the local knowledge of …

Fix `porcelain.fetch`

---

dulwich/tests/test_index.py

Fixes #574 
The current test suite fails when running on a new enough Python version on Windows to have the `os.symlink` function available (Python 3.2 and later), but without privileges to create symlinks, which is the general case when not running as administrator.
This fix skips the symlink creation tests when the test process either does not have symlink capabilities, or has them but not enough privilege to create symlinks.

More robust symlink creation test for Windows

---

dulwich/porcelain.py
dulwich/tests/test_porcelain.py

Argument `recursive` was not being used in the function, which led to the tree of sub directories in a given repo to be listed, even if not specified.

Fix ls_tree function

---

dulwich/refs.py
dulwich/tests/test_refs.py

The Git reference storage model has one dark corner which is that it doesn't support creating `refs/foo/bar/baz` when `refs/foo/bar` is already a reference. The reason for this is that internally the references are stored as a directory tree, so if `.git/refs/foo/bar/baz` exists, `.git/refs/foo/baz` is a directory on the filesystem so it cannot be a reference.
The flip side of this is that Git must clean up parent directories when it removes a reference, or it would not be possible to create `refs/foo/bar` after removing `refs/foo/bar/baz`. The canonical implementation does that.
This PR introduces the same clean-up in dulwich.

refs: Clean-up parent directories when removing references

---

bin/dulwich
dulwich/porcelain.py
dulwich/tests/test_porcelain.py

This has been used by Pext to generate the version strings shown in the about screen rather successfully for months now, so I feel okay enough with this to submit it upstream. It doesn't support all git describe does (no flags are supported), but it's a simple basic implementation that would fulfil the most common use cases.

Simple describe implementation

---

dulwich/porcelain.py
dulwich/tests/test_porcelain.py

A couple entangled issues here:
1. In`check_ignore`: 
- `path_to_tree_path` was not being used appropriately, basically `path = os.path.relpath(path, r.path)` was done twice
- paths in index are always bytes, but paths passed to `ignore_manager` should always be strings: had to add some encoding/decoding
2. In `path_to_tree_path`:
- not checking if the tree_path did indeed start by repo_path 
- types again, after all calls to `path_to_tree_path` the returned path is used to check if it's in the index: might as well always return bytes. also small bug possible when replacing the separator, if the input path was in fact bytes.

Fix path_to_tree_path

---

dulwich/porcelain.py

Without such, the `errstream` parameter only applies to
```python
errstream.write(b'Checking out ' + head.id + b'\n')
```
All other output, like that generated by `fetch()` (called by `clone()`), is
written, unwanted, to `porcelain.default_bytes_err_stream`.

Pass the <errstream> parameter through from porcelain.clone() to porcelain.fetch().

---

appveyor.yml
dulwich/porcelain.py
dulwich/tests/test_porcelain.py

I think theoretically this should fix #652, but I'm not sure how to properly test this, as I don't have a Windows machine myself so can't try it under pythonw.exe myself.

Add fallback for unavailable stdout/stderr

---

AUTHORS
dulwich/client.py
dulwich/tests/test_client.py

I noticed it was impossible to clone a GitLab hosted repository using dulwich when its url is not suffixed by `.git`. For instance while it is possible to do a `git clone` on this repository https://git.gnu.io/gnu/gnuio, trying to do the same operation with dulwich gives me the following:
```
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from dulwich.porcelain import clone
>>> clone('https://git.gnu.io/gnu/gnuio')
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/antoine/dev/dulwich/dulwich/porcelain.py", line 353, in clone
depth=depth, **kwargs)
File "/home/antoine/dev/dulwich/dulwich/porcelain.py", line 1119, in fetch
depth=depth)
File …
```

Fix url redirect location handling in HttpGitClient

---

dulwich/porcelain.py
dulwich/tests/test_porcelain.py

Resolves #398. 
Implements `dulwich.porcelain.clean`, which is equivalent to `git clean -fd`. In the future, it will be straightforward to add an option to also remove ignored files )(equivalent to `git clean -fdx`).

porcelain clean (issue 398)

---

dulwich/patch.py
dulwich/tests/test_patch.py

When generating a diff in a repository with dirty submodules, CGit is using
the subproject terminology. I couldn't find the reasoning why or since when it
has been doing it but https://stackoverflow.com/q/4873980/2996250 seems to
indicate it has been the case since 2011 at least.
It has no real impacts as submodules information in diff are mostly ignored by
`git apply` but this makes Dulwich behavior closer to CGit one.

Rename submodule into subproject in diff to match CGit behavior

---

dulwich/porcelain.py

Currently staged is a dict with lists for each type of staged paths as it implements get_tree_changes.

Fixing porcelain's status documentation.

---

dulwich/repo.py
dulwich/tests/test_repository.py

While investigating RabbitVCS issue https://github.com/rabbitvcs/rabbitvcs/issues/121, I tracked the problem  down to dulwich.
This PR is a proposed fix.
Thanks for considering it.

Allow configured email addresses to be pre-quoted as "<...>".

---

dulwich/_diff_tree.c

Missed in 8f73bc51e2620820fa1d3aa2c109a3aa3fbe5bc8
This was causing misbehaviour on big endian, e.g. s390x (multiple test failures).
Fixes: #735

A missed Py_ssize_t conversion for PY_SSIZE_T_CLEAN

---

dulwich/porcelain.py
dulwich/tests/test_porcelain.py

Lookup remote origin url when using `porcelain.pull()`.
This should allow `porcelain.pull()` work when git repository has a remote origin defined.

Feature: Pull remote url

---

dulwich/hooks.py

client_refs contains bytes, which can't be combined into str.
p.communicate also expects bytes.
( see: https://docs.python.org/3/library/subprocess.html#subprocess.Popen.communicate )

fix PostReceiveShellHook to handle bytes properly on Python 3

---

dulwich/client.py

The git server code that parse the deepen packet (https://github.com/git/git/blob/2f268890c2cd2f115424936bbee27f8269080e5e/upload-pack.c#L811) will fail if the deepen is set to 0, special case this too to not send it.
This is the second fix for #747

Don't send a depth of 0 on a shallow fetch

---

dulwich/client.py

This seems the correct thing to do because it enables the user to control the exact bytes that are used to encode the URL.

Use utf-8 instead of file system encoding to convert path to str.

---

setup.py

If trying to install dulwich on Python 2, the following error will be printed:
"ERROR: Package 'dulwich' requires a different Python: 2.7.18 not in '>=3.5'"

Add python_requires metadata to setup.py.

---

dulwich/diff_tree.py

This is a faster and more idiomatic way of using `itertools.chain`. Instead of computing all the items in the iterable and storing them in memory, they are computed one-by-one and never stored as a huge list. This can save on both runtime and memory space.

Use chain.from_iterable in diff_tree.py

---

dulwich/tests/compat/test_repository.py

This is a continuation of #778 . I don't know whether this file is important enough for this change, given it's a test file in the compat package. Your call.

Use chain.from_iterable in compat/test_repository.py

---

dulwich/porcelain.py

The loop target is named `error`, not `status` (which is another `porcelain` function).

Correct name error in porcelain.push()

---

dulwich/client.py

While working in my own environment the archive was failing for me
with "invalid response ACK" message". Looks like my git (hosted gerrit)
returns ACK instead of "ACK\n" expected by that code. As the shell
git clients works well with my server, seems like both versions should be
supported by the library.
I've tested it locally with my hosted git.
Fixes #805

Allow "ACK" and "NACK" (without new line) in client.py

---

dulwich/stash.py

Fixes minor bugs in `stash.Stash`
* use `os.fsencode`/`os.fsdecode` when needed so that bytes/strings are not mixed
* make `__getitem__` and `__len__` work properly (use `list(stashes())` instead of `_stashes()`)

Fix minor stash bugs

---

dulwich/object_store.py
dulwich/tests/test_object_store.py

On Python 3, dulwich crashes with `TypeError` if there is a relative path in `info/alternates`.
This PR reproduces and fixes the problem in tests, and also an issue with comments uncovered while investigating my actual issue.
For more context, here's the [issue reported by one of my users](https://foss.heptapod.net/heptapod/heptapod/-/issues/370). Happens in GitLab because  the path to pool is relative.
Since this is I believe my first contribution to Dulwich, do you want an issue to supplement that?

Fix for byte problems (TypeError) reading alternate paths 

---

dulwich/porcelain.py
dulwich/repo.py
dulwich/tests/test_porcelain.py

Adds `no_verify=False` flag to `porcelain.commit` and `repo.do_commit` to skip execution of `pre-commit` and `commit-msg` git hooks - equivalent to `git commit -n/--no-verify`

commit: add no_verify flag to skip pre-commit hooks

---

dulwich/tests/test_missing_obj_finder.py

There is a small typo in dulwich/tests/test_missing_obj_finder.py.
Should read `technically` rather than `techically`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, techically -> technically

---

NEWS
dulwich/porcelain.py
dulwich/tests/test_porcelain.py

As per this issue: https://github.com/dulwich/dulwich/issues/793 `porcelain.status` fails if the repo you are interrogating contains any symlinks. This generally means that the functionality will not work inside any `virtualenv`s.
In this PR I've added a flag to `get_untracked_paths` to avoid ignored symlinks and fix the above issue. 
I have added some new tests and also an entry to the NEWS (although not sure how good it is!).
Please let me know if you have any questions or concerns. All feedback is greatly appreciated.
Thanks,
Matt

Issue 793: Fix failure in get_untracked_paths when the repository contains symlinks

---

dulwich/client.py
dulwich/tests/test_client.py

Before this change, credential files consisting of only one
line without end-of-line would work.
The change is actually stripping any leading and trailing whitespace,
but that shouldn't be a problem. The shared test setup is updated with
a newline because that should be a fairly common case.

client/credentials: ignore end-of-line character

---

dulwich/ignore.py
dulwich/tests/test_ignore.py

This PR should fix #836
Tests are passing but what was the reason for `find_matching` to stop after the first match?

Fix find_matching to stop returning after the first match

---

dulwich/porcelain.py
dulwich/tests/test_porcelain.py

porcelain.status: support untracked symlinks to paths outside the repo

---

dulwich/stash.py

Currently, if a repo has pre-commit hooks and any of them fail, `stash.push` will also fail (even though the types of changes you would stash in typical use cases would likely be expected to fail any pre-commit hooks)
- `stash.push` now uses `do_commit(no_verify=False, ...)` to skip running any pre-commit hooks

stash: skip pre-commit hooks when generating stash commits

---

dulwich/hooks.py
dulwich/server.py

Problem:
1) self.proto.write_sideband is expecting "bytes", but was getting a "str".
2) HookError(x) expects a string for a nicer output.
Solution:
Pass a str to HookError (decode the command output),
and then pass bytes to write_sideband (encode it).

post-receive hook: fix an exception when the command fails with an error

---

docs/tutorial/remote.txt
dulwich/cli.py
dulwich/client.py
dulwich/contrib/test_swift_smoke.py
dulwich/object_store.py
dulwich/porcelain.py
dulwich/protocol.py
dulwich/repo.py
dulwich/server.py
dulwich/tests/compat/test_client.py
dulwich/tests/test_client.py
dulwich/tests/test_object_store.py
dulwich/tests/test_repository.py

Currently, dulwich supports shallow clone/fetch from non-local servers, but there is no way to deepen or unshallow via `fetch`. `determine_wants` will see that the tip commit for a given ref is up to date and skip the fetch.
After this PR:
- fetch `determine_wants` now takes an optional `depth` parameter containing fetch depth.
- if depth is set to `DEPTH_INFINITE` (requesting a complete unshallowing of the repo), all refs will be fetched
- otherwise, if depth is set and nonzero, the current available depth for a given ref will be checked, and the ref will be fetched if the requested fetch depth is greater than the current depth.

client: support deepening/unshallowing refs on fetch

---

NEWS
dulwich/porcelain.py
dulwich/tests/test_porcelain.py

When using `porcelain.get_untracked_paths` with `exclude_ignored`, currently every untracked path is checked to see if it is gitignored. If a directory is gitignored, we can skip checking the remainder of the files inside that directory - from the documentation for [gitignore](https://git-scm.com/docs/gitignore):
> Git doesn’t list excluded directories for performance reasons, so any patterns on contained files have no effect, no matter where they are defined.
Changes after this PR:
- `porcelain.get_untracked_files`: no longer walks ignored directories for performance reasons. The path to the ignored dir (including trailing slash) will be yielded if `exclude_ignored=False`, but individual files within the directory will not be included.
- `porcelain.add`: now only returns path to ignored …

porcelain.status: skip traversal of gitignore untracked dirs

---

.github/workflows/pythonpackage.yml
dulwich/objects.py
dulwich/porcelain.py
dulwich/tests/test_porcelain.py

This PR fixes two compatibility issues with git around signed tags, and adds support for specifying a signing Key ID to use when creating a signed tag.
The first issue is the serialisation logic for tags. When git creates a signed tag, it includes a new line at the end of the buffer being signed. If this isn't included, then git will not parse the tag signature and if it's included when serialising the tag signature itself, git will be performing signature verification on different data to what was signed, leading to signature verification failure.
The second issue this PR fixes is with the GPG signature mode used. By specifying that a detached signature is being made, Dulwich will create the same format of tag signature as git (see …

Fix two bugs in signed tag support and add ability to specify a key id to use for signing

---

dulwich/config.py
dulwich/tests/test_config.py

Will close #865 
from https://github.com/dulwich/dulwich/issues/865#issuecomment-828274471
> I guess checking for the system config on windows isn't exactly straightforward since it depends on where the user installed Git (it will be in `<path-to-git-installation>/etc/gitconfig`
> 
> But it reasonable for dulwich to at least check `C:\Program Files\Git\etc\gitconfig` (current default Git for Windows install location) and `C:\ProgramData\Git\config` (alternate system config location in vista+ from the [git docs](https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup))

config: check default system paths on windows

---

dulwich/tests/__init__.py
dulwich/tests/test_porcelain.py

Fixes windows specific CI test failures that resulted from the crlf & windows system config changes
Now that dulwich reads CGit global config on windows, it now picks up `autocrlf = True` from the system wide config that was ignored before. This made some windows autocrlf test bugs show up (the tests assumed autocrlf was always disabled by default on all platforms which is no longer the case)

tests: fix windows crlf CI issues

---

dulwich/objects.py
dulwich/tests/compat/__init__.py
dulwich/tests/compat/test_porcelain.py
dulwich/tests/test_porcelain.py

- `tag.verify()` is used in porcelain tests and replaces CGit calls
- Checks that dulwich & CGit can verify each others' signed tags moved to `tests.compat.test_porcelain`

objects.Tag: add verify() for gpg signature verification

---

.github/workflows/pythonpublish.yml

Latest release is missing mac and linux wheels. From https://github.com/dulwich/dulwich/runs/2651889610?check_suite_focus=true
```
======================================================================
ERROR: test_default_key (dulwich.tests.test_porcelain.TagCreateSignTests)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/Users/runner/work/dulwich/dulwich/dulwich/tests/test_porcelain.py", line 1108, in test_default_key
import gpg
ModuleNotFoundError: No module named 'gpg'
======================================================================
ERROR: test_non_default_key (dulwich.tests.test_porcelain.TagCreateSignTests)
----------------------------------------------------------------------
Traceback (most recent call last): …
```

gha: publish: don't forget gpg

---

dulwich/config.py
dulwich/tests/test_config.py

Previously, reading a config file that started with an UTF-8 BOM would die with an error. This was originally reported to hg-git, where we use `Config.from_file()` for reading `.gitmodules`.
Originally reported to `hg-git` on [Heptapod](https://foss.heptapod.net/mercurial/hg-git/-/issues/354).

config: disregard UTF-8 BOM when reading file

---

dulwich/repo.py

Using `list()` to format fs_paths will not only access type `str` but also access type `tuple` and type `set`.

use list() to change fs_paths to list

---

dulwich/__main__.py
dulwich/cli.py

The first value in `sys.argv` is the name of the script invoked, with actual arguments following. Previously, any attempt to invoke the script would yield e.g.:
$ dulwich
No such subcommand: /path/to/dulwich
This was presumably never noticed due to `python -m dulwich.cli` explicitly passing in `sys.argv[1:]`.
I've also added support for invoking the package directly, using `python -m dulwich`, consistent with e.g. `pip`. `python -m dulwich.cli` still works as well.

Unbreak `dulwich` script

---

dulwich/object_store.py
dulwich/tests/test_object_store.py
dulwich/tests/test_pack.py
dulwich/tests/utils.py

This is a follow-up to #892 which broke the test suite on Windows. I haven't what Git does with permissions on that platform, so it seems better to leave it be.

don't create unwritable files on Windows

---

dulwich/hooks.py

Problem:
p.communicate expects bytes in and bytes out.
When out_data is not empty, the code formatting err_msg was producing an exception.
Solution:
Formatting everything as bytes literals.

post-receive hook: error encoding fixes for Python 3.

---

dulwich/client.py
dulwich/tests/test_client.py

- Adds `ssh_command` parameter to `SSHGitClient` and `SSHVendor.run_command`
- If specified, `ssh_command` will be used instead of the default `ssh` or `plink[.exe]` executables when we run SSH via subprocess (in both `SubprocessSSHVendor` and `PLinkSSHVendor`)
- Existing options for host/port/user/password/etc will still be appended to the command and should not be included in `ssh_command`
- `ssh_command` is ignored for the paramiko contrib vendor
- `SSHGitClient` will use `GIT_SSH` or `GIT_SSH_COMMAND` environment variables if they are set (with precedence given to `ssh_command` > `GIT_SSH_COMMAND`, `GIT_SSH`)
- We do not autodetect the vendor variant when `GIT_SSH` or `GIT_SSH_COMMAND` is set, currently we assume that the user has selected the appropriate dulwich SSH vendor and that …

client: add support for GIT_SSH_COMMAND

---

dulwich/pack.py
dulwich/tests/test_pack.py

On very large git repositories, an excessive amount of memory is used. This reuses the
patch mentioned in the issue [1] and fixes the impacted tests.
Test plan:
```
$ ... setup venv (on bullseye so python3.9)
$ workon dulwich
$ time make clean check  # happy
----------------------------------------------------------------------
Ran 1414 tests in 64.353s
OK (skipped=14, expected failures=1)
make clean check  6.51s user 3.78s system 15% cpu 1:05.37 total
```
[1] #894

pack.DeltachainIterator: Execute a DFS walk instead of BFS

---

dulwich/clone.py
dulwich/porcelain.py
dulwich/repo.py
dulwich/tests/test_porcelain.py
dulwich/tests/test_repository.py

- unifies behavior between `porcelain.clone` and `Repo.clone` in `dulwich/clone.py`
- cloned repo now uses the remote's default branch name if it differs from dulwich `DEFAULT_REF` (previously `porcelain.clone` would always use `refs/heads/master` regardless of the remote branch name)
- adds `branch=...` parameter for porcelain and repo clone equivalent to `git clone --branch` for checking out specific branch or tag name after clone (instead of checking out default branch)

porcelain.clone: add branch option equivalent to 'git clone --branch'

---

dulwich/client.py
dulwich/porcelain.py
dulwich/refs.py
dulwich/repo.py

Initial work fixing cloning of remote repositories in porcelain.
Needs direct unit tests for GitClient.clone().

Initial work fixing cloning of remote repositories in porcelain

---

dulwich/client.py
dulwich/porcelain.py
dulwich/repo.py

Re-enable progress support in clone methods for reporting fetch progress
- Adds `progress=` in `Repo.clone`, `client.clone`
- Uses `progress=errstream.write` in `porcelain.clone`

clone: re-add progress support

---

.github/workflows/pythonpackage.yml
dulwich/contrib/requests_vendor.py

Workaround for using no_proxy environment variable as discussed in #932 by using requests as a higher-level alternative to urllib3. It's based on dulwich/cotrib/paramiko_vendor.py

Add requests_vendor as higher level http client alternative

---

dulwich/config.py
dulwich/contrib/diffstat.py
dulwich/fastexport.py
dulwich/pack.py
dulwich/server.py
dulwich/tests/__init__.py
dulwich/tests/test_ignore.py
dulwich/tests/test_objects.py
dulwich/tests/test_patch.py
dulwich/tests/test_porcelain.py

Remove unnecessary #noqa comments.
This merge proposal was created automatically by the [Janitor bot](https://janitor.jelmer.uk/yesqa).
For more information, including instructions on how to disable
these merge proposals, see https://janitor.jelmer.uk/yesqa.
You can follow up to this merge proposal as you normally would.
The bot will automatically update the merge proposal to resolve merge conflicts
or close the merge proposal when all changes are applied through other means
(e.g. cherry-picks). Updates may take several hours to propagate.
Build and test logs for this branch can be found at
https://janitor.jelmer.uk/yesqa/pkg/dulwich/394e4017-0497-4760-b54d-6d9e3223d1f2.

Remove unnecessary #noqa comments

---

dulwich/repo.py
dulwich/tests/compat/test_repository.py

See #926 more details on the problem as it relates to Dulwich.
This ensures that the repo's common dir is used as the source of a config, rather than the control dir. This matches the behavior documented in the git-worktree documentation for [details on configuration files.](https://git-scm.com/docs/git-worktree#_details) A test case is also added to ensure the behavior is as expected.
**Test Plan:**
[x] Added test case
[x] `make build && sudo make install` to build patched version, run with test case script from #926 bug report
[x] `make check` tests all pass other than skipped/expected failures

Ensure git config is available in a linked working tree

---

dulwich/porcelain.py

sys.stdout.buffer is failing on Jupyter notebook environments. Fix #950

Fix dulwich.porcelain.diff_tree default outstream value

---

dulwich/client.py
dulwich/config.py
dulwich/object_store.py
dulwich/porcelain.py
dulwich/refs.py
dulwich/repo.py

Some miscellaneous typechecking additions.
I'm afraid this is rather un-systematic, I'm not keen to volunteer to sort out the typing in this project in its entirety!  But it is kind of annoying that dulwich has  a `py.typed` declaring that it is typed; and that most of its interface does not actually have type annotations...
So I have added annotations only on the parts of the interface that I am using in the project that is currently of interest to me, so that I can get _that_ to typecheck cleanly - and also just enough internal annotations to satisfy mypy here.
This is very far from completing the typing: but I think it's going in the right direction - and if others were to do the same for the parts of the interface that they cared about then we'd get all the way to done, one step at a …

miscellaneous typechecking

---

.github/workflows/pythonpublish.yml

Was missed in https://github.com/jelmer/dulwich/commit/94a68a899b6139c35c8a10e683218ee2ba755105, which resulted in failed wheel builds https://github.com/jelmer/dulwich/runs/6442441328?check_suite_focus=true.

gha: publish: don't forget to install paramiko

---

dulwich/porcelain.py
dulwich/tests/test_porcelain.py

The idea is to more closely match `git`'s `-u/--untracked-file` flag and behaviour:
- `untracked_files="no"` returns no untracked files
- `untracked_files="all"` (dulwich default) returns all untracked files
- `untracked_files="normal"` (git default) is not implemented (see discussion at https://github.com/jelmer/dulwich/pull/956)

porcelain: rename walk_untracked kwarg to untracked_file

---

dulwich/contrib/test_paramiko_vendor.py

Gentoo patches out server support from paramiko for security reasons.
Since dulwich uses it only for testing, use the knob to explicitly
reenable it.

Explicitly reenable paramiko server on Gentoo for tests

---

.github/workflows/pythonwheels.yml

changes introduced in `f473b9f1..02ac0dc9` moved the twine upload step to a separate job, which is missing the `pip install twine` step
fixes #968

gha: don't forget to install twine

---

.github/workflows/pythonwheels.yml

Unfortunately wheel publishing got broken in https://github.com/jelmer/dulwich/commit/978cd0115bf16eaeca510e55028d12fc5d9344ba
We now upload built wheels into one `dist` artifact and then publish them all at once in one job, saving on workers.
Related to #963

gha: don't forget to upload wheels

---

dulwich/porcelain.py
dulwich/tests/test_porcelain.py

This PR adds a test that pushes to Dulwich itself. The main motivation is to reproduce #977 without relying on outside infrastructure.
While at it, I added a small test for pulling into an empty repository, only to discover that it failed. So I fixed that :slightly_smiling_face:

Add tests for pushing to the embedded server

---

dulwich/client.py
dulwich/tests/test_client.py

When authenticating using basic auth and only providing username (no password) the default value of `None` was cast to string, resulting in an attempt to authenticate using `<username>:None` instead of providing an empty password.
This broke authentication when providing an auth token as username (`https://token@github.com/...`)
Also see https://github.com/iterative/dvc/issues/7898#issuecomment-1157564615

client: fix basic auth with empty password

---

dulwich/client.py
dulwich/config.py
dulwich/ignore.py
dulwich/repo.py

Continuing to add type annotations to config-related classes.
That there are places in the code that put booleans into the configuration remains a wart, and its influence grows as the types pass that fact along.  It might be a worthwhile clean up to have [this code](https://github.com/jelmer/dulwich/blob/bbf100b63fb00ebb4a1d0ca698b1abe337611bae/dulwich/repo.py#L368-L374) use the strings "true" and "false" and remove `bool` from `Value` and `ValueLike`...

more typechecking

---

dulwich/config.py
dulwich/porcelain.py
dulwich/repo.py

As discussed in #984 
I've left in place some code that is in some sense not required any more, for backwards compatibility - I don't know how much you worry about such things.  Specifically these fragments are only needed to support users who are currently setting boolean values - happy to remove / update them if you're willing to make the clean break.
https://github.com/jelmer/dulwich/blob/9d9b5072223e4276793a7c6005786cb87f96cb08/dulwich/config.py#L197-L198
https://github.com/jelmer/dulwich/blob/9d9b5072223e4276793a7c6005786cb87f96cb08/dulwich/config.py#L376
https://github.com/jelmer/dulwich/blob/9d9b5072223e4276793a7c6005786cb87f96cb08/dulwich/config.py#L608-L612

Special case boolean config values

---

dulwich/client.py
dulwich/config.py

Apologies for the stream of MRs, I intend this to be the last!
I realised that after making the `set()` change for booleans in the way that you suggested, the code that I had previously kept for backwards-compatibility can in fact be removed.  So here's one last piece of tidying on that.

tidying up the boolean config change

---

NEWS
dulwich/cli.py
dulwich/porcelain.py
dulwich/submodule.py
dulwich/tests/test_porcelain.py

Add basic commands for submodule listing and adding. See #506

Add basic commands for submodule listing and adding

---

dulwich/tests/compat/utils.py

Copy PATH into the environment used by subprocess.Popen().
This makes it possible to use Git binaries installed in non-standard
locations, such as ~/bin. And it allows running compat tests on OpenBSD,
where "git" sits in /usr/local/bin by default, and where /usr/local/bin
is not in the default PATH of the shell.

compat tests: honour PATH environment variable in run_git()

---

.github/workflows/pythonpackage.yml

5.x started reporting new issues which were making CI fail.

gha: temporarily pin flake8 to 4.0.1

---

dulwich/tests/test_porcelain.py

`gpg` is one of the extra optional packages, but when running tests, it's currently required (otherwise, several tests fail with `ImportError`). This PR skips those tests if `import gpg` fails.

Allow missing gpg package during tests

---

requirements.txt
setup.py

pyOpenSSL and urllib3[secure] are deprecated in the upcoming release (1.26.12)
https://github.com/urllib3/urllib3/issues/2680

Deprecation notice about urllib3[secure]

---

.github/workflows/pythonwheels.yml

Earlier PR #1001 failed, see https://github.com/jelmer/dulwich/runs/7951988430?check_suite_focus=true#step:14:102.
> /opt/python/cp311-cp311/bin/pip install --upgrade --no-cache-dir pip
/entrypoint.sh: line 26: /opt/python/cp311-cp311/bin/pip: No such file or directory
Updating the GitHub action `RalfG/python-wheels-manylinux-build` to `v0.5.0` fixes the issue.

bump RalfG/python-wheels-manylinux-build to v0.5.0

---

dulwich/objects.py
dulwich/porcelain.py
dulwich/repo.py
dulwich/tests/test_porcelain.py

This PR adds functionality to sign commits.
[Added in Git 1.7.9](https://raw.githubusercontent.com/git/git/master/Documentation/RelNotes/1.7.9.txt).
The implementation functions similarly to tag signing already implemented.
RFC on some details:
- using ```copy()``` instead of string slicing for signature verification
- ```sign()``` writing to ```gpgsig``` instead of ```_gpgsig``` (imitating ```Tag.sign()```)
- gpg functionality is only tested for in ```test_porcelain```, should there be such testing in ```test_objects``` or ```test_repo```?

Implement commit signing

---

dulwich/file.py

Improves file system integrity.
This modification should minimize the possibility of corrupted files for (Windows) systems without UPS and the possibility for incomplete shutdowns, power failure or hard reset.
The positive effect shows, if one of the above incidents happens after a completed writing git access (e.g. commit)
Without fsync when the system (Windows) is not shutdown properly, files may have proper length but contain only '0' bytes.

Added flush before fsync

---

docs/tutorial/porcelain.txt

Currently, the porcelain documentation does not mention that `porcelain.clone` supports authentication using the `username` and `password` parameters.
I think it would be nice to mention this especially for new users of the library like me, who go straight to the porcelain section of the documentation because they just want to clone a repository in Python. It took me a while to figure out that authentication is possible, so I'd like to ease that burden for all future new users of Dulwich by explicitly stating that possibility :)

Document authentication with porcelain.clone

---

dulwich/tests/test_porcelain.py

Ignore errors when deleting GNUGPG home directory.
Sometimes these fail because of race conditions with gnupg agent socket files.
Fixes #1000
Thanks to Matěj Cepl for the patch.

Ignore errors when deleting GNUGPG home directory

---

.github/workflows/pythonwheels.yml

This enhances the Github Actions configuration to create wheels for 32-bit Windows.
As win32 is still a valid platform for python, this helps using dulwich on this python versions, as no compiler/compilation is required on package installation.

Add 32 bit architecture wheels for windows

---

dulwich/porcelain.py

Ensure the configuration is loaded in dulwich.porcelain.clone.

Ensure the configuration is loaded in dulwich.porcelain.clone

---

.github/workflows/pythonpackage.yml
dulwich/porcelain.py
dulwich/tests/test_porcelain.py

This PR adds functionality to detect local timezone offsets to porcelain.
[date-formats.txt](https://raw.githubusercontent.com/git/git/v2.3.0/Documentation/date-formats.txt).
~~The implementation optionally supports [```python-dateutil```](https://github.com/dateutil/dateutil) to parse ISO 8601 formatted strings.~~
RFC on some details:
- move ```parse_timezone_format()``` out of porcelain?
- different ordering of formats?
- use author date instead of committer date in ```tag_create()```? (currently works like C git)
IMO, only porcelain should support timezone detection. All "internal/low-level" functions should just default to 0.

Implement timezone offset detection

---

.github/workflows/pythonpackage.yml
dulwich/client.py
setup.py

Drop use of certifi to find ca certificate path.
This seems to be having adverse affects where we specify an incorrect path in some cases. Fixes #1025
Increment minimum urllib3 to >= 1.25 just to be sure; not strictly necessary -
we're already trying to be explicit about whether we want verification.
This was originally introduced in 48e2ef8c2f2c65a33ad3276458791c19ef208c1a, but
urllib3 now verifies certificates by default.
See also https://urllib3.readthedocs.io/en/latest/user-guide.html#certificate-verification
thanks to @dimbleby  for help with the archeology on this one :)

Drop use of certifi to find ca certificate path

---

dulwich/client.py
dulwich/protocol.py

Apply insteadOf to rsync-style location strings as well
Previously, these were just applied to plain URLs.
Fixes python-poetry/poetry#6329

Apply insteadOf to rsync-style location strings as well

---

.github/workflows/pythontest.yml
.github/workflows/pythonwheels.yml

Fix wheels uploads: don't upload wheels with unsupported platform tag.
This was down to a missing dash, *manylinux*.whl matches 6 extra wheels with
platform tag linux_aarch64; *-manylinux*.whl doesn't.
Fixes #1034

Fix wheels uploads: don't upload wheels with unsupported platform tag

---

.github/workflows/pythonwheels.yml

Hey there, here's an attempt at building musl wheels using [cibuildwheel](https://github.com/pypa/cibuildwheel) to help with #1007.
Set to build wheels on the following architectures for python versions 3.6-3.11:
```
CIBW_ARCHS_LINUX: x86_64 aarch64
CIBW_ARCHS_MACOS: x86_64 arm64 universal2
CIBW_ARCHS_WINDOWS: AMD64
```
Go ahead and tweak as wanted according to the `CIBW_ARCHS*` options documented [here](https://cibuildwheel.readthedocs.io/en/stable/options/#archs).
I'm coming from an issue with installing poetry on alpine in https://github.com/nikolaik/docker-python-nodejs, started with https://github.com/python-poetry/poetry/pull/5428 released in poetry [v1.2.0](https://github.com/python-poetry/poetry/releases/tag/1.2.0)
Resulting in the following build artifacts: …

Start building using cibuildwheel

---

dulwich/archive.py
dulwich/tests/test_archive.py

Support non-ascii characters in filenames in tar streams.

Support non-ascii characters in filenames in tar streams

---

NEWS
dulwich/refs.py
dulwich/tests/test_refs.py

Catch SymrefLoop in set_if_equals.
(Dominic's change in https://github.com/jelmer/dulwich/pull/1042 + tests)
Fixes #1042

Catch SymrefLoop in set_if_equals

---

dulwich/tests/compat/test_utils.py
dulwich/tests/compat/utils.py

This makes it easier to determine why a Git command failed. In my case, while exploring Git-protocol-v2 support, it is very helpful to see what git-http-backend complains about when my WIP implementation sends an invalid request.

display stderr output from git programs run by the test suite

---

dulwich/bundle.py
dulwich/client.py
dulwich/object_store.py
dulwich/pack.py
dulwich/porcelain.py
dulwich/protocol.py
dulwich/server.py
dulwich/tests/test_client.py
dulwich/tests/test_object_store.py
dulwich/tests/test_pack.py
dulwich/tests/utils.py

Factor out chunking of pack files, avoiding use of BytesIO.

Factor out chunking of pack files, avoiding use of BytesIO

---

dulwich/pack.py
dulwich/tests/test_pack.py
dulwich/tests/utils.py

Abort deltify() calls when reaching max size limit.

Abort deltify() calls when reaching max size limit

---

dulwich/index.py

Raise specific exception when index format is unsupported

Raise specific exception when index format is unsupported

---

dulwich/objects.py
dulwich/repo.py
dulwich/tests/test_objects.py
dulwich/tests/test_repository.py

This fixes #1068.
The check for correctly formed identities in `check_user_identity` (used in `do_commit`) is still weaker than the one in `check_identity`. The difference is in checking for `<` and `>`.

Improve check_identity and check_user_identity

---

NEWS
dulwich/index.py
dulwich/porcelain.py
dulwich/repo.py
dulwich/tests/test_index.py

On Windows, provide a hint about developer mode when creating symlinks fails due to a permission error
Fixes #1005

On Windows, provide a hint about developer mode when creating symlinks fails due to a permission error

---

NEWS
dulwich/objects.py
dulwich/refs.py
dulwich/repo.py
dulwich/walk.py

Add more typing.
Remove check for single-str argument to Repo.get_walker(), from when Dulwich
was python2-only.

Add more typing

---

dulwich/credentials.py
dulwich/tests/__init__.py
dulwich/tests/test_credentials.py

Import misc url-matching functions for credentials helpers.
From @dtrifiro's https://github.com/jelmer/dulwich/pull/976

Import misc url-matching functions for credentials helpers

---

tox.ini

Latest Debian stable has this and adding it makes development easier. Also looks like this no longer supports Python 3.5 so removing

Add Python 3.9 into tox config

---

tox.ini

Since upstream doesn't predominantly use tox, just remove all extra boilerplate so tox will work out of the box with whatever Python is.

Simplify tox setup

---

dulwich/client.py
dulwich/tests/test_client.py

This small change would allow the usage of
`http_proxy='' command`
as for example in
`http_proxy='' dvc list ...`
in bash scripts to temporary overwrite a proxy configuration by environment variables.

empty proxy environment variables are now ignored

---

NEWS
dulwich/cli.py
dulwich/pack.py
dulwich/porcelain.py

This feature allows the ``dulwich pack-objects`` command to complete in a somewhat reasonable amount of time on small repositories, provided a pack file which can provide deltas already exists.
Reusing deltas from an existing pack file avoids deltification overhead while creating a new pack file. This optimization is especially important when serving clones and fetches from a server.
For testing purposes, add two options to ``dulwich pack-objects``:
--deltify: enables deltification and delta-reuse
--no-reuse-deltas: disables delta-reuse during deltification
The write_pack_objects() now accepts an optional Pack file object argument which enables reuse of deltas.
If deltification is enabled and delta-reuse is not explicitly disabled, the pack_objects() routine in porcelain.py picks a …

allow for reuse of existing deltas while creating pack files

---

dulwich/cli.py
dulwich/file.py
dulwich/porcelain.py
dulwich/refs.py
dulwich/tests/test_porcelain.py
dulwich/tests/test_refs.py

This contains the following changes:
* [Handle more errors when trying to read a ref](https://github.com/jelmer/dulwich/commit/2339d6a0a8e76573ad1828cd33b3ecfdd859e87b)
Some files aren't just not there, but actually invalid. Different operating systems handle that differently, but rather than getting cute and specific, treat any error when reading a ref as indicating that it's not there.
(As an example, double quotes raise one type of error on Windows; non-UTF-8 paths another on macOS, and e.g. ZFS on Linux triggers a third if UTF-8 is active.)
See: https://foss.heptapod.net/mercurial/hg-git/-/issues/397
* [Make the GitFile context manager discard writes on exceptions](https://github.com/jelmer/dulwich/commit/199d7d6d7d9f43c90484a1d2c390602cf706e353)
* [Add 'pack-refs' …

Add 'pack-refs' command

---

.github/workflows/pythontest.yml
NEWS
docs/tutorial/remote.txt
dulwich/__init__.py
dulwich/bundle.py
dulwich/cli.py
dulwich/client.py
dulwich/contrib/swift.py
dulwich/greenthreads.py
dulwich/object_store.py
dulwich/objects.py
dulwich/pack.py
dulwich/porcelain.py
dulwich/repo.py
dulwich/server.py
dulwich/tests/compat/test_client.py
dulwich/tests/compat/test_pack.py
dulwich/tests/test_bundle.py
dulwich/tests/test_client.py
dulwich/tests/test_greenthreads.py
dulwich/tests/test_object_store.py
dulwich/tests/test_pack.py
dulwich/tests/test_repository.py
dulwich/tests/test_server.py
dulwich/walk.py
setup.cfg

Refactor pack handling.
This causes a number of low-level API changes, so I'm going to bump the major 
version for dulwich along with this.
Among other things, Dulwich now reuses pack deltas
when communcating with remote servers - bringing a big boost to network
performance.

Refactor pack handling

---

dulwich/pack.py

It returns `ShaFile` type not `bytes`, spotted by the [Jenkins build](https://jenkins.softwareheritage.org/blue/organizations/jenkins/DLDG%2Fmaster/detail/master/9/pipeline) of Software Heritage Git loader.

pack: Fix Pack.__getitem__ return type

---

dulwich/client.py
dulwich/tests/test_client.py

Some git servers can redirect a repository URL using an absolute-path URI reference as value of the `Location` HTTP header as allowed by [RFC 7231 Section 7.1.2](https://www.rfc-editor.org/rfc/rfc7231#section-7.1.2).
```console
$ curl -I https://codeberg.org/ashwinvis/radicale-sh.git
HTTP/2 307 
cache-control: no-store, no-transform
content-type: text/html; charset=utf-8
location: /ashwinvis/radicale-auth-sh
set-cookie: i_like_gitea=7b9a4d2494e520a3; Path=/; HttpOnly; SameSite=Lax; Secure; SameSite=Lax
set-cookie: _csrf=rcOoJeB1NS-JKRoc8ve8til2uVs6MTY3ODc0MDA0NTE0MzgwMzI1MQ; Path=/; Expires=Tue, 14 Mar 2023 20:40:45 GMT; HttpOnly; SameSite=Lax; Secure; SameSite=Lax
set-cookie: macaron_flash=; Path=/; Max-Age=0; HttpOnly; SameSite=Lax; Secure; SameSite=Lax
date: Mon, 13 Mar 2023 20:40:45 …
```

client: Handle absolute path as redirect location in HTTP client

---

dulwich/client.py
dulwich/repo.py
dulwich/tests/test_porcelain.py

When cloning a repo with detached head we do not need to do anything w/setting default branches or trying to match the origin's HEAD
This makes dulwich clone consistent with CGit, where cloning a source repo with detached head makes the resulting dest repo also have a detached head (with no default or upstream tracking branches set)
```
$ git clone src-repo dst-repo
Cloning into 'dst-repo'...
done.
Note: switching to 'dbfb510657c332184640b3b1329979194fb3bead'.
You are in 'detached HEAD' state.
...
$ cd dst-repo
$ git status
Not currently on any branch.
nothing to commit, working tree clean
$ cat .git/HEAD
dbfb510657c332184640b3b1329979194fb3bead
$ cat .git/config
[core]
...
[remote "origin"]
url = /Users/pmrowla/git/scratch/test-detached-clone/src-repo
fetch = …
```

clone: fix cloning repo with detached head

---

dulwich/pack.py

I have encountered
```
UnboundLocalError: local variable 'i' referenced before assignment
```
on this line
https://github.com/jelmer/dulwich/blob/df1660cb6e65b4a211b8f5c8f547293ec65664d0/dulwich/pack.py#L1068
in `dulwich==0.21.3`, presumably because this function depends on `self.read_objects()` being non-empty. I encounter this deterministically when I do encounter it, but I don't know the exact conditions to reproduce yet. I think it's related to cache situations when reading from the same repo more than once in the same script, but it seems to only happen for certain files. For context, I am a DVC user and have encountered it with `dvc.api.open()` and also when calling `dvc import` from the CLI.
This PR adds `i = 0` above the for loop, which fixes the bug for me (then when …

initialize pack entry count to 0 in pack.PackStreamCopier.verify()

---

dulwich/repo.py

For the moment, allow non-kwargs to _init_files

For the moment, allow non-kwargs to _init_files

---

dulwich/objects.py

If the first item of the tuple is not None, then the second item is guaranteed not to be None either.
This is motivated by Software Heritage calling this function and getting the value for three (non-None) keys:
* https://gitlab.softwareheritage.org/swh/devel/swh-loader-git/-/blob/5cbe435407a14726c3e1c353eeee3681d8a2c2ac/swh/loader/git/converters.py#L189
* https://gitlab.softwareheritage.org/swh/devel/swh-loader-git/-/blob/5cbe435407a14726c3e1c353eeee3681d8a2c2ac/swh/loader/git/converters.py#L279
so mypy complained. Not a big deal though; I can work around it with assertions: https://gitlab.softwareheritage.org/swh/devel/swh-loader-git/-/merge_requests/153/diffs

Define a stricter return type for _parse_message

---

dulwich/objects.py

The `_hashlib` import seems to be awkward for some python installations, as reported over in poetry.
Since it's only used for typechecking, only make the import during typechecking.

_hashlib import is needed only for typechecking

---

dulwich/client.py
dulwich/tests/test_client.py

Some git servers can send a `Content-Type` header containing a `charset` directive. 
```shell
$ echo -e "0079want 034350e047bbb1892a917c51f065f2e8125a6bf7 multi_ack multi_ack_detailed ofs-delta shallow side-band-64k thin-pack\n0032want 034350e047bbb1892a917c51f065f2e8125a6bf7\n0032want 67106b8421ca9e5fe77e46766e754e29390abb89\n00000009done\n" | curl -i -X POST --data-binary @- -H "Content-Type: application/x-git-upload-pack-request" https://hacktivis.me/git/blog.git/git-upload-pack
HTTP/2 200 
server: nginx/1.23.3
date: Wed, 05 Jul 2023 10:41:01 GMT
content-type: application/x-git-upload-pack-result; charset=utf-8
expires: Fri, 01 Jan 1980 00:00:00 GMT
pragma: no-cache
cache-control: no-cache, max-age=0, must-revalidate
x-frame-options: sameorigin
x-content-type-options: nosniff …
```

client: Fix content type check in AbstractHttpGitClient._smart_request

---

dulwich/config.py

Current windows Git installations include separate git exe's in `Git/cmd/git.exe` and `Git/mingw64/bin/git.exe`. The mingw64 build will be in the PATH when the user is in git-bash, and the native `cmd/git.exe` build will be in the PATH in native windows shells (cmd.exe or powershell).
The system level gitconfig that gets used by either `git.exe` is located in `Git/etc/gitconfig`, but the existing windows gitconfig lookup behavior only searches `Git/mingw64/etc/gitconfig`

config: check both `git/etc` and `git/mingw64/etc` on windows

---

dulwich/index.py
dulwich/porcelain.py
dulwich/repo.py
dulwich/tests/test_index.py

More refactoring of index
- Split out SerializedIndexEntry
- Add a ConflictedIndexEntry class that holds references to {ancestor, this, other} entries

More refactoring of index

---

dulwich/client.py

There are some packets (like NAK) which have no sha. This does not change them to be handled but you get in exception always the command that failed to be unpacked instead of strange exception about there not being enough values to unpack.

Raise GitProtocolError on unexpected pkt

---

dulwich/index.py

Clarify that Index.__getitem__ returns a Index or ConflictedIndexEntry
Fixes #1205

Clarify that Index.__getitem__ returns a Index or ConflictedIndexEntry

---

dulwich/graph.py
dulwich/tests/test_graph.py

Following the logic of actual git, this pr modifies graph.py to use a priority queue and commit time stamps to greatly speed up "can fast forward" calculations by using commit time to know which parent to walk up first and when to stop the search.
The use of commit time stamps necessitates a tweak to the test_graph.py.

for use with graph.py new pr

---

dulwich/protocol.py

Version 2 of the Git protocol adds a new message delimiter which is distinct from the flush packet. Recognize such delimiters in the read_pkt_line() method of the Protocol class, such that pkt-lines will still be split as expected when reading protocol-v2 messages.

recognize Git protocol-v2 delim-pkt message separators

---

dulwich/client.py

See issue #868. Since OP did not react, I opened this requested PR.

Issue #868 - Add fallback if win32api.FindExecutable cannot find git

---

dulwich/_pack.c

The git loader used by Software Heritage recently reported the following error while processing the following repository: https://github.com/BlockSocUNSW/Blocksoc_Net.
```
ApplyDeltaError: Unexpected source buffer size: 18446744072185159680 vs 2770575360
File "swh/loader/core/loader.py", line 441, in load
self.store_data()
File "swh/loader/git/base.py", line 80, in store_data
for obj in self.get_contents():
File "swh/loader/git/loader.py", line 505, in get_contents
for raw_obj in self.iter_objects(b"blob"):
File "swh/loader/git/loader.py", line 490, in iter_objects
for obj in PackInflater.for_pack_data(
File "dulwich/pack.py", line 1440, in _walk_all_chains
yield from self._follow_chain(offset, type_num, None)
File "dulwich/pack.py", line 1495, in _follow_chain
unpacked = …
```

_pack: Fix some big left-shifts of unsigned char 

---

dulwich/config.py
dulwich/tests/test_config.py

A git submodule needs two items in its config: url to clone from, path to clone to. If either is missing, core git simply ignores this submodule entry. Dulwich should do the same.
(closes: #411)

config: handle malformed git submodules 

---

.github/workflows/python-distributions.yml

cf #975
Comments:
- for obvious reasons, it's hard for me to test this end-to-end
- the build process here respects your `MANIFEST.IN` in a way that whatever you are currently doing seems not to
- the most conspicuous difference is the omission of `testdata`, maybe you want to add `graft testdata`

publish sdist from github

---

.github/workflows/python-distributions.yml

Install twine when uploading to pypi.

Install twine when uploading to pypi

---

dulwich/graph.py

The shebang is useless in the `graph.py` file:
```
$ chmod +x dulwich/graph.py
$ PYTHONPATH=. dulwich/graph.py
Traceback (most recent call last):
File "/tmp/dulwich/dulwich/graph.py", line 25, in <module>
from .lru_cache import LRUCache
ImportError: attempted relative import with no known parent package
$
```
So let's remove it.
See also #1230.

Remove shebang from graph.py

---

disperse.conf

Disable pypi uploads in disperse; this is now down by the GitHub actions workflow

Disable pypi uploads in disperse; this is now down by the GitHub actions workflow

---

dulwich/client.py

Some doc-strings were talking about smart Git servers which do not come into the picture when the transfer protocol is just local disk access.

tweak doc-strings in LocalGitClient for clarity

---

dulwich/client.py

Previously, we were also expecting a shallow update response when advertising that we have shallow commits.
This was the cause of unexpected pkt lines in reported in https://github.com/jelmer/dulwich/pull/1202

Only expect a shallow update when requesting a depth

---

dulwich/client.py

Fixes https://github.com/jelmer/dulwich/issues/1225

Wrap all urllib3 read ProtocolErrors as GitProtocolError

---

pyproject.toml

We still need this for the utils module

Fix installation of tests package

---

dulwich/repo.py
tests/test_repository.py

`extensions.worktreeconfig` was checked in a way that was not case-insensitive, but git config settings should be case insensitive. This behavior led to problems since the documentation describes the setting as `worktreeConfig` and GitHub Actions started setting the option with this casing.
Fixes https://github.com/jelmer/dulwich/issues/1285

Handle alternate case for worktreeconfig setting

---

dulwich/client.py
tests/test_client.py

Fix regression introduced in a5cc324 and add test to cover the `urllib3.exceptions.ProtocolError` wrapping.

client: Fix NameError 'urllib3' is not defined

---

fuzzing/fuzz-targets/fuzz_repo.py

The `fuzz_repo` fuzz target is crashing the fuzzer because of a known exception case where the time ofsets in commit messages can raise a `ValueError`, which is not an interesting in the context of fuzzing.
Closes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=69045

Update Known Exception Handling in `fuzz_repo` to Prevent False Positives

---

dulwich/pack.py
tests/test_pack.py

Dulwich could be driven into an infinite loop by creating a pack file which contains a ref-delta that refers to the deltified object itself as the delta's base, indexing this pack file as a thin-pack, and then trying to access the packed object.
Fix this problem and add a test case which triggers the issue if the fix is reverted (caution: the test will loop forever).
Found via a bug in the Software Heritage Git Loader test suite which created such a pack file:
https://gitlab.softwareheritage.org/swh/devel/swh-loader-git/-/merge_requests/184/

detect and reject ref-deltas which use an object as its own delta base

---

pyproject.toml

the build depends on setuptools: but it also depends on setuptools-rust - and those things are correctly declared as build requirements in pyproject.toml

dulwich does not depend on setuptools

---

pyproject.toml

These have been failing for a while, with no obvious fix. See #1303 for details.

Skip failing Mac OS X wheel builds for now

---

dulwich/cli.py
dulwich/client.py
dulwich/contrib/paramiko_vendor.py
dulwich/porcelain.py
dulwich/protocol.py
tests/compat/test_client.py
tests/test_client.py

Implement Git protocol version negotiation and use Git protocol v2 for fetches if supported. For now, the observable behaviour of Dulwich is equivalent regardless of protocol version, except that two new features may be used if the server supports Git protocol v2.
The first feature is a reference prefix list which may be used to filter refs server-side. This can be used to reduce the size of the initial reference listing announced by the server. Reducing the size of this announcement was a major design goal for protocol v2 to avoid sending of very large announcements when a repository contains a lot of references. This feature is intended as an optimization which servers are free to ignore depending on available server-side resources. Therefore, users of Dulwich should still be prepared …

add initial support for Git protocol v2

---

fuzzing/oss-fuzz-scripts/build.sh
fuzzing/oss-fuzz-scripts/container-environment-bootstrap.sh

Updates the OSS-Fuzz container environment & build script to build and install Dulwich with all optional features enabled and refines dictionary handling.
- Increases the fuzz-able surface area of the most interesting (from a fuzzing & security testing perspective) Dulwich APIs, enabling future fuzz harnesses improvements to specifically target these features in tests.
- Enhances flexibility of fuzzer seed data generation steps to improve dictionary quality and simplify seed corpus management for all fuzz targets.
- Unset problematic OSS-Fuzz provided `$RUSTFLAGS` to prevent build issues that inhibit PyO3 based Rust extension compilation.
- Install Python dependencies with specific features (`fastimport`, `gpg`, `paramiko`, etc.).
- Added "drop-in" support for inclusion of seed corpora …

Fuzzing: Build Fuzz Tests with Rust Extensions and Optional Features

---

.github/workflows/pythontest.yml
Cargo.lock
crates/diff-tree/src/lib.rs
crates/objects/src/lib.rs
crates/pack/src/lib.rs
dulwich/objects.py
tests/test_objects.py

* Avoid copying names in sorted_tree_items
* Add some more tests for sorted_tree_items
* Make sure we're actually testing the rust implementations and not accidentally the Python ones

Various minor rust improvements

---

NEWS
dulwich/object_store.py
dulwich/objectspec.py
dulwich/pack.py
dulwich/tests/test_object_store.py
tests/test_pack.py

This allow scanning an object store for a specific SHA prefix. The default implementation is naive and scans the entire key space, but specific implementations have more efficient approaches, improving performance.,

Add ObjectStore.iter_prefix

---

dulwich/client.py
tests/compat/test_client.py

This adds missing compat tests for symref handling in git protocol v2 and fixes a bug in the HTTP client implementation uncovered by the tests.

Test symrefs handling for git protocol v2

---

dulwich/client.py

Github's SSH git protocol v2 server returns a useless reference list which only contains "HEAD" unless we explicitly ask for the "refs/" prefix.
Fixes issue #1389

use a default ref-prefix when fetching with git protocol v2

---

dulwich/client.py
tests/compat/test_client.py

This aligns protocol-v2 behaviour with earlier protocol versions. Add test coverage for this behaviour, too.
Fixes issue #1410

return peeled refs from GitClient.get_refs() if protocol-v2 is used

---

pyproject.toml
setup.py

When a pure build is requested, no compiled extensions are produced. The setuptools_rust dependency ends up imported-but-not-used. Teach setuptools to avoid build-requiring it in this case.
Closes: https://github.com/jelmer/dulwich/issues/1405

build: respect the "pure" argument at metadata generation time

---

dulwich/porcelain.py

This argument currently only works for v2 and is untested.
when encoding refspecs, handle the absence case (thanks to @stspdotname in https://github.com/jelmer/dulwich/pull/1416 for finding this)
Also, don't provide separate encoding argument for refspecs. This is consistent with other arguments. Callers that really need a non-standard encoding can do their own encoding and pass in a bytestring.

Drop broken refspecs argument for porcelain.clone

---

dulwich/client.py

This makes it so both "version 2" and "version 2\n" (and any alternatives with more whitespace) are accepted as a successful v2 response.
Fixes #1423

Strip pkt-line when negotiating Git protocol v2

---

dulwich/diff_tree.py
dulwich/objects.py
dulwich/refs.py

In the process of stating to use Dulwich (for https://gitlab.com/perm.pub/hidos/-/commits/sshsig), I added the following type hints to get mypy to pass with strict setting (in hidos).
Seems like a very safe merge.
I'll probably have some more type hints in the next few days. I'll ping you when I think  I don't have any more type hints to add this week.

add easy type hints to some function returns

---

dulwich/objects.py

Some more type hints to keep sshsiglib and hidos strict. I couldn't quickly figure out proper typing for all params and returns, but it made mypy much happier.

type hints for ShaFile.copy and Tree.lookup_path

---

dulwich/objects.py
tests/compat/test_porcelain.py
tests/test_objects.py

Fixes #1429, incorrect signature verification for commits with an empty message, as encoded by CGit.

Fix empty message serialization

---

README.rst

Maybe I just misunderstood the Github Actions and Python required line.

Readme: Python 3.9 is tested and required, not 3.6

---

dulwich/porcelain.py
tests/test_porcelain.py

porcelain: respect 'abbrev' argument when describing annotated-tagless repositories

---

dulwich/repo.py

Add docstrings for constructors of repo.Repo and repo.MemoryRepo
They previously inherited the docstring of repo.BaseRepo, which told you not to call them!

Docstrings for constructors of repo.Repo and repo.MemoryRepo

---

dulwich/cli.py

A couple of problems encountered while attempting to use `dulwich pull` with Git protocol v2:
* Mismatched argument name / attribute access (`protocol_version` vs `args.protocol`)
* Mismatched attribute value type (`list[int]` vs `int`)
Also some minor consistency fixups for `dulwich clone` (neither of these should affect functionality):
* Remove a redundant `dest` parameter
* Use consistent Python argument indentation / trailing-comma style for param

cli: protocol argument consistency and fixups

---

dulwich/cli.py

As per the [Python `getopt` documentation](https://docs.python.org/3.9/library/getopt.html#getopt.getopt), add an equals symbol to require that the message option has a corresponding value (argument).
Resolves #1508.

cli: adjust 'message' argument parsing to require a value

---

dulwich/cli.py

Adjust positional argument parsing for `add` and `remove` CLI methods to collect `pathlib.Path` results.
Resolves #1509.

cli: adjust parsing of positional path arguments

---

dulwich/porcelain.py
tests/test_porcelain.py

Basically #1513 with tests.
Fixes #1510

Handle empty commit messages in porcelain.log

---

dulwich/cli.py

This branch / pull request prepared using these commands (except for 2e1791b1e50e05a6332434a3a6f6f25319230989, 17780fff50f32f15ab56939f3c74ca832d568326, cd0450a3e7608b76fcfb623120656a01fdc6f780 and 04136969ac29f3f82a10d9a3c0faec4ab231afc1 that were committed -- but not pushed -- using the `git-scm` tooling).
NB: the `reset` command, despite being modified here to accept a treeish, doesn't appear to reset the HEAD commit correctly (`dulwich log` continues to report from the pre-reset commit, instead of the expected resetted-to treeish).

cli: add basic branch management commands

---

tests/test_objects.py

This small PR resolves the `datetime` deprecation warnings by replacing `utcfromtimestamp()` with `fromtimestamp()` and solving:
```python
/home/runner/work/dulwich/dulwich/tests/test_objects.py:620: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
```
Which you can see in the [CI logs](https://github.com/jelmer/dulwich/actions/runs/14574702612/job/40878265958#step:13:18).

Resolve datetime deprecation warnings

---

dulwich/client.py

When hacking on the Software Heritage git loader, I noticed it was no longer possible to request fetching a thin pack file using latest dulwich release.
After a git bisect session, I identified the regression was due to the recent support of git protocol v2 by dulwich that is now used by default when fetching a pack file (2b975ec).
After some research on the subject, it turns out that with git protocol v2, requesting a thin pack must be done through an argument to the [fetch command](https://git-scm.com/docs/protocol-v2#_fetch) sent to the git server.
I can confirm that thin-pack feature with git protocol v2 works as expected after these small changes .

client: Ensure thin_packs parameter is honored with git protocol v2

---

NEWS
dulwich/client.py

This will prevent any indefinite hangs, and instead turn them into exceptions. Hopefully that will help drill down why this is happening for some users.

SubprocessClient: timeout after 60s of inactivity when closing channel

---

NEWS
dulwich/ignore.py
dulwich/porcelain.py
tests/compat/test_check_ignore.py
tests/test_ignore.py

Patterns like ``!data/*/`` now correctly unignore direct subdirectories while still ignoring files in the parent directory, matching Git's behavior. The ``is_ignored()`` method now documents that directory paths should end with ``/`` for consistent behavior.
Also, support quote_path flag.
Fixes #1203

Fix gitignore pattern matching for directory negation patterns

---

NEWS
dulwich/porcelain.py
tests/test_porcelain.py

* Fix ``porcelain.add()`` when adding repository root path or directories.
Previously, adding the repository path itself would incorrectly stage
``b'./'`` instead of the actual untracked files, leading to
repository corruption.  Fixed #1178
* Improve ``porcelain.add()`` documentation to correctly describe default
behavior. Fixes #895

Two fixes for add handling

---

NEWS
dulwich/repo.py
tests/test_repository.py

This allows creating repositories with different format versions by specifying the repository format version (0 or 1) which sets the core.repositoryformatversion configuration value.

Add support for format argument to Repo.init() and Repo.init_bare()

---

NEWS
crates/objects/src/lib.rs
tests/test_objects.py

The Rust implementation was incorrectly treating submodules (mode 0o160000) as directories during tree sorting. This happened because it used a simple bitwise AND check (mode & S_IFDIR != 0) which matches both directories (0o40000) and submodules (0o160000).
Fixed by properly checking the file type using the S_IFMT mask, matching the Python implementation's behavior with stat.S_ISDIR().
Added test case that reproduces the issue and verifies both implementations now produce identical sorting results.
Fixes #1325

Fix Rust implementation of sorted_tree_items() for submodules (#1325)

---

NEWS
dulwich/config.py
dulwich/file.py
dulwich/ignore.py
dulwich/index.py
dulwich/object_store.py
dulwich/pack.py
dulwich/porcelain.py
dulwich/refs.py
dulwich/repo.py
tests/test_config.py
tests/test_ignore.py
tests/test_index.py
tests/test_porcelain.py
tests/test_refs.py
tests/test_repository.py

Functions that accept file paths now support pathlib.Path objects in addition to strings and bytes. This includes repository operations, configuration file handling, ignore file processing, and all major entry points.
Fixes #1074

Add support for os.PathLike objects throughout the API

---

NEWS
dulwich/pack.py
tests/compat/test_pack.py
tests/test_pack.py

Initial work on pack index v3

---

NEWS
dulwich/cli.py
dulwich/porcelain.py
tests/test_porcelain.py

This implements the unpack-objects command that extracts all objects from a pack file and writes them as loose objects to the repository's object store.

Add unpack-objects plumbing command

---

NEWS
dulwich/ignore.py
tests/compat/test_check_ignore.py

When checking if directories are ignored, users must include a trailing slash (e.g., "dir/" instead of "dir") to get correct results. This matches Git's behavior.
Added compatibility test to verify behavior matches Git.
Fixes #972

docs: Clarify trailing slash requirement for directory ignore checks

---

dulwich/refs.py
tests/test_refs.py

The set_if_equals() method was incorrectly updating all refs in a symbolic reference chain instead of just the requested ref. This was because it used follow() to get all refs in the chain and then updated all of them.
This caused issues where updating a symbolic ref would incorrectly modify the ref it pointed to.

Fix DictRefsContainer.set_if_equals() to only update requested ref

---

NEWS
dulwich/cli.py
dulwich/porcelain.py
tests/test_porcelain.py

Add revert functionality to dulwich.porcelain and CLI that creates new commits to undo changes from specified commits while preserving history.
Fixes #1599

Implement git revert command (#1599)

---

NEWS
dulwich/annotate.py
dulwich/cli.py
dulwich/fastexport.py
dulwich/patch.py
dulwich/porcelain.py
dulwich/tests/test_annotate.py
dulwich/walk.py

This is complete, but still needs tests.

Implement annotate. Fixes #245

---

NEWS
dulwich/pack.py

apply_delta was raising AssertionError instead of ApplyDeltaError in the pure Python implementation when the Rust extension was not available.
Fixes #1606

Convert assertion to ApplyDeltaError in apply_delta function

---

tests/test_porcelain.py

The bug described in issue #1247 where top-level untracked files were not detected by get_untracked_paths() and status() appears to have already been fixed. Adding a specific test case to prevent regression.
Fixes #1247

Add test for issue #1247 (top-level untracked files detection)

---

NEWS
dulwich/index.py
tests/test_porcelain.py

When resetting to a remote branch, files that were deleted in the remote were not being removed locally due to incorrect path normalization on Windows. The issue was that paths were being compared with different separators (backslash vs forward slash).
This fix normalizes paths to use forward slashes consistently, matching Git's internal representation, ensuring files are properly deleted when they don't exist in the target tree.
Fixes #840

Fix porcelain.reset --hard to delete files not in target tree

---

NEWS
dulwich/porcelain.py
tests/test_porcelain.py

porcelain.status: Support untracked_files="normal" and make it the default

---

NEWS
dulwich/porcelain.py
tests/test_porcelain.py

Previously, porcelain.remove() would fail when called from a directory other than the repository root because it interpreted relative paths as relative to the current working directory. This change makes relative paths relative to the repository root.
Fixes #821

Fix porcelain.remove() to work from any directory

---

NEWS
dulwich/index.py
dulwich/porcelain.py
dulwich/repo.py
tests/test_index.py

- Add blob_normalizer parameter to update_working_tree function to support
line ending conversions during checkout operations
- Update porcelain.pull() and porcelain.reset() to pass blob_normalizer
from repository configuration
This enables proper line ending handling when checking out files from
the repository to the working directory.

Add blob_normalizer support to update_working_tree

---

NEWS
dulwich/objectspec.py
tests/test_objectspec.py

Previously, checking out an annotated tag would fail with a KeyError because parse_commit() didn't dereference tag objects to their target commits. This fix adds tag dereferencing to all code paths in parse_commit(), ensuring that annotated tags are properly resolved to their target commits.
Fixes #1638

Fix parse_commit to properly dereference annotated tags

---

NEWS
dulwich/index.py

Previously, dulwich would write empty extensions to the index file, causing unnecessary bloat. Now we filter out extensions with no data before writing.
Fixes #1643

Only write Git index extensions when they contain meaningful data

---

NEWS
dulwich/porcelain.py
tests/test_porcelain.py

Verify that porcelain.push returns SendPackResult with per-ref status information. This functionality was already implemented but lacked test coverage.
Fixes #780

Add test for porcelain.push return value

---

dulwich/client.py
dulwich/dumb.py
tests/compat/test_dumb.py
tests/test_client.py
tests/test_dumb.py

I noticed the dumb transport protocol was added in latest dulwich release and tried to use that new feature in the Software Heritage git loader so we could remove our [homemade support](https://gitlab.softwareheritage.org/swh/devel/swh-loader-git/-/blob/67b322effb00e81d7696a0ce676ec0d3241143ef/swh/loader/git/dumb.py) of it and only relies on dulwich.
I stumbled across a couple of bugs after plugging dulwich dumb transfer protocol into the SWH loader, this pull request fixes the issue I observed and adds more tests.
After these fixes, the loader works fine when encountering a repository that only offers dumb transfer protocol. Almost all of our git loader tests are still passing apart a couple that need some mocking adaptation due to the changes in the loader implementation.

Some fixes for the dumb transfer protocol

---

dulwich/porcelain.py
tests/test_porcelain.py

The remove command checks if files have been modified before removing them from the index. However, it was comparing the raw file content against the normalized index content, which could lead to false positives when line endings differ.
Now the remove command applies checkin normalization to the file content before comparing it with the index, ensuring accurate modification detection regardless of line ending differences in the working tree.

Apply filters when checking file modifications in remove command

---

dulwich/porcelain.py

Git applies clean/smudge filters by default during checkout operations to ensure files in the working tree have the expected format (e.g., proper line endings). This change makes Dulwich's checkout behavior consistent with Git's.
The checkout() function now gets the blob normalizer from the repository and passes it to update_working_tree() to ensure filters are applied when materializing files.

Apply filters during checkout operations

---

dulwich/attrs.py

The previous implementation had issues with updating attributes for existing patterns. This refactors the method to correctly track and update the pattern index, ensuring attribute modifications are properly persisted in the patterns list.

Fix GitAttributes.set_attribute to properly update existing patterns

---

NEWS
tests/test_porcelain.py

- Replace hardcoded 7-character hash with dynamic length based on uniqueness
- Update find_unique_abbrev to find shortest unique prefix (minimum 7 chars)
Fixes #824

Fix porcelain.describe() hash length to match git describe behavior

---

NEWS
dulwich/refs.py
tests/test_refs.py

This is inspired by [an issue filed in hg-git](https://foss.heptapod.net/mercurial/hg-git/-/issues/401); essentially, writing a _lot_ of unchanged references is quite slow, due to the `fsync()` implied in re-writing the file. Although we could fix this within hg-git, it seems to me that the general optimisation might apply to other users of Dulwich, so this PR makes it so that it avoids acquiring the lock to a ref if that ref already matches the expected update.

refs: optimise writing unchanged refs

---

NEWS
dulwich/object_store.py
dulwich/pack.py
dulwich/porcelain.py
tests/test_object_store.py
tests/test_porcelain.py

This implements Git's core.commitGraph configuration setting which controls whether commit-graph files are used for performance optimization. When enabled (default), commit graph files are used to speed up parent lookups in operations like find_shallow(), get_depth(), and commit ancestry traversal.
Also adds write_commit_graph() porcelain function to generate commit graphs.

Add support for core.commitGraph configuration setting

---

NEWS
dulwich/config.py
tests/test_config.py

These variables allow overriding the default global and system configuration paths.
Fixes #1193

Add support for GIT_CONFIG_GLOBAL and GIT_CONFIG_SYSTEM environment variables

---

dulwich/porcelain.py
tests/test_porcelain.py

This commit addresses the issue where `dulwich status` incorrectly reported cache directories (like `.ruff_cache/`, `.pytest_cache/`, `__pycache__/`) as untracked files, even though they contained `.gitignore` files that ignored all their contents.
The implementation maintains Git-compatible behavior and only performs recursive checks when necessary (when `exclude_ignored=True` and a directory is entirely untracked), preserving performance for common cases.
Fixes the issue where cache directories were incorrectly reported as untracked.

Fix gitignore handling for nested directories

---

NEWS
dulwich/objectspec.py
tests/test_objectspec.py

Support more complicated revision syntax

---

NEWS
dulwich/index.py
tests/test_index.py

Fixes #203 (hopefully) where filenames containing Unicode characters like 'À' were incorrectly encoded/decoded on Windows, resulting in corruption during clone and checkout operations.
The fix adds proper handling of UTF-8 encoded tree paths on Windows by:
- Converting UTF-8 tree paths to filesystem encoding when creating files
- Converting filesystem paths back to UTF-8 when storing in git trees
- Adding a tree_encoding parameter (defaulting to 'utf-8') to relevant functions for future flexibility
Added comprehensive test coverage for Unicode filename handling.

Fix Unicode filename encoding on Windows

---

dulwich/dumb.py

In pratice, it is better to check objects existence in pack files first to avoid flooding git server with numerous HTTP requests.
For instance to load the following git repository only supporting dumb transfer protocol: https://tinc-vpn.org/git/tinc
```
$ curl -I https://tinc-vpn.org/git/tinc/info/refs?service=git-upload-pack
HTTP/1.1 200 OK
Date: Tue, 15 Jul 2025 14:06:00 GMT
Server: Apache/2.4.62 (Debian)
Strict-Transport-Security: max-age=31556952
Last-Modified: Sun, 07 Apr 2024 15:29:31 GMT
ETag: "1f4b-615835af9bff4"
Accept-Ranges: bytes
Content-Length: 8011
```
using the SWH git loader with that [merge request](https://gitlab.softwareheritage.org/swh/devel/swh-loader-git/-/merge_requests/204) applied, it takes around 30 minutes without the changes in that PR and around 40 seconds …

dumb: Optimize number of HTTP requests sent to git server

---

dulwich/errors.py
dulwich/index.py
dulwich/porcelain.py
dulwich/stash.py
tests/test_index.py
tests/test_porcelain.py

- Replace iter_tree_contents with diff_tree for massive performance improvement
- Only process files that actually changed between trees
- Add safety check to prevent overwriting uncommitted changes by default

Optimize update_working_tree and prevent overwriting uncommitted changes

---

dulwich/objects.py
tests/test_object_store.py

Allow Tree.lookup_path to handle empty byte strings by returning the tree itself with S_IFDIR mode. This matches the expected behavior when looking up the root of a tree.

Support empty path in Tree.lookup_path

---

NEWS
pyproject.toml

Require ``typing_extensions`` on Python 3.10.

---

NEWS
tests/test_cli.py

The worktree CLI commands expect to be run from within a repository directory. Updated the test methods to change to the repo directory before running commands and restore the original directory afterward.
Fixes #1738

Fix worktree CLI tests to properly change to repository directory

---

NEWS
dulwich/worktree.py
tests/test_worktree.py

Add a context manager for creating temporary worktrees that are automatically cleaned up on exit. This simplifies the common pattern of creating a worktree for temporary operations.
Also add exist_ok parameter to add_worktree to support creating worktrees in directories that already exist (e.g. from tempfile.mkdtemp).

Add temporary_worktree context manager

---

NEWS
dulwich/index.py
tests/test_index.py

Fix a regression introduced in 0.23.1 where checkout operations on Windows would fail with "Cannot create directory, parent path is a file: b'C:'" error.
The issue occurred in _ensure_parent_dir_exists when validating parent paths. The original implementation manually split paths and reconstructed them, which didn't correctly handle Windows drive letters or UNC paths.
The fix uses os.path.dirname() to properly walk up the directory tree, letting Python's built-in path handling deal with all platform-specific cases including:
- Windows drive letters (C:\, D:\, etc.)
- UNC paths (\\server\share\...)
- Unix paths (/home/user/...)
This approach is more robust and eliminates the need for platform-specific special cases.
Fixes #1751

Fix Windows path handling regression in checkout operations

---

NEWS
dulwich/config.py
tests/test_config.py

Previously, Dulwich would load multiple gitconfig files on Windows including defunct ones from old installations.
Changes:
- Modified get_win_system_paths() to only return the current Git config path
- Added get_win_legacy_system_paths() for diagnostic/migration purposes
- Added debug logging to show which gitconfig files are loaded
Fixes #1732

Fix Windows config loading to only use current Git installation

---

NEWS
dulwich/cli.py
dulwich/porcelain.py
dulwich/rebase.py
tests/test_rebase.py

This adds support for interactive rebase (`git rebase -i`) with all standard git rebase commands: pick, reword, edit, squash, fixup, drop, exec, and break.
Fixes #1696

Add interactive rebase support

---

dulwich/refs.py
dulwich/repo.py
tests/test_refs.py
tests/test_stash.py

This commit adds a proper support for reading and iterating over
references from shared and per-worktree "refs" directory depending on
the reference name.
It also updates the reflog writing to use the correct directory based
on the reference.
Fixes https://github.com/iterative/dvc/issues/10821.
Related documentation: https://git-scm.com/docs/git-worktree#_refs

refs:  handle per-worktree and shared refs on read and on reflog writes

---

NEWS
dulwich/line_ending.py
tests/test_line_ending.py
tests/test_porcelain.py

When core.autocrlf = input is set, files with CRLF line endings were incorrectly showing as unstaged even when their content hadn't changed. This was because TreeBlobNormalizer.checkin_normalize() was not applying the clean filter (CRLF to LF conversion) for existing files when autocrlf=input was set.
The fix ensures that when autocrlf=input is configured, all text files are normalized during checkin operations, including when checking status. This makes Dulwich's behavior consistent with Git.
Fixes #1770

Fix handling of CRLF line endings with core.autocrlf = input

---

.github/workflows/pythontest.yml
CONTRIBUTING.rst
Makefile
pyproject.toml

This fixes a couple frustrations I ran into in my recent PRs:
- Adds a single `make` target to run all style checks that will be required for a PR
- Adds the missing dev dependency on `codespell`
- Updates `CONTRIBUTING.rst` to mention how to install Dulwich in dev mode, the required checks for PRs, and fixes an apparent typo in the coding style section (which seems to be the opposite of what the code actually uses)
- Fixes code blocks in `CONTRIBUTING.rst`  for proper rendering on GitHub
You might also want to consider using the `make` targets inside the PR test workflow instead of inlining their corresponding commands, to guarantee they won't drift apart, but that's a larger decision and I leave it up to you.

Improve new contributor experience

---

NEWS
dulwich/cli.py
dulwich/porcelain.py
tests/test_porcelain.py

This PR adds a new function porcelain.shortlog to the Dulwich porcelain module. The function summarizes commits by author, similar to Git’s git shortlog.

Add porcelain.shortlog function to summarize commits by author

---

dulwich/cli.py
tests/test_cli.py

This PR implements the --remotes flag for the dulwich branch command, which lists remotes branches.
https://github.com/jelmer/dulwich/issues/1847

add --remotes to branch command

---

NEWS
dulwich/filters.py
dulwich/lfs.py
dulwich/line_ending.py
dulwich/repo.py
dulwich/sparse_patterns.py
tests/test_filters.py
tests/test_line_ending.py
tests/test_sparse_patterns.py

The ProcessFilterDriver was spawning a new subprocess for every file operation, causing severe performance degradation for large repositories (minutes instead of milliseconds for git status).
This commit implements the Git filter process protocol to use a single long-running process for all filter operations:
- Add support for filter.<driver>.process configuration
- Implement Git filter process protocol (version 2) with proper pkt-line format
Fixes #1789

Fix subprocess filter performance issues (#1789)

---

dulwich/cli.py
dulwich/porcelain.py
tests/test_cli.py
tests/test_porcelain.py

Implements the --no-merged flag for the dulwich branch command, 
which lists branches that have not been merged into the current branch
https://github.com/jelmer/dulwich/issues/1847

add --no-merged to branch command 

---

NEWS
dulwich/filters.py
dulwich/line_ending.py
dulwich/whitespace.py
tests/test_line_ending.py
tests/test_whitespace.py

* Add core.whitespace configuration support for whitespace error detection
* Add core.safecrlf configuration support for safe CRLF conversion checks
* Refactor LineEndingFilter with from_config classmethod for cleaner code
Fixes #1806

Add support for core.whitespace and core.safecrlf
