jelmer/dulwich

appveyor.yml

This change installs pywin32 when running tests on appveyor.

Appveyor: install pywin32.

---

dulwich/tests/test_hooks.py
dulwich/tests/test_porcelain.py
dulwich/tests/test_repository.py

This solves a bunch of Sharing violation errors on windows.

Close all mkstemp files.

---

dulwich/porcelain.py
dulwich/server.py
dulwich/tests/__init__.py
dulwich/tests/compat/test_client.py
dulwich/tests/test_repository.py

This, fixes 19 tests on windows, bringing it to, when combined with my other PR's
Ran 999 tests in 154.254s 
FAILED (failures=1, errors=1, skipped=116)
https://ci.appveyor.com/project/garyvdm/dulwich/build/1.0.96/job/l30h2dvrcvcxsba9#L1189
Getting close :-)

Windows test suite fixes.

---

dulwich/index.py
dulwich/repo.py
dulwich/tests/test_index.py
dulwich/tests/test_repository.py

Another alternative to #290.
I realised I can reorder the commits, so that there are less changes between the commits, which I hope will make it easier to review.

Checkout paths2

---

dulwich/_diff_tree.c
dulwich/_objects.c
dulwich/_pack.c
dulwich/tests/test_repository.py

```
$ tox -e py34
...
Ran 1048 tests in 30.973s
OK (skipped=132)
```

Make the C modules compatible with Python 3

---

relicensing-apachev2.txt

Agree to relicensing.

---

dulwich/objects.py
dulwich/tests/test_objects.py

As it turns out, a git object can be terminated by the last header,
without empty lines. In that case, dulwich currently "eats" the last
header line, which is obviously wrong.
When such a case happens, return an object with a None message instead
of an empty line. We make sure that serialization/deserialization
still works as expected.

Support completely empty messages in git objects

---

dulwich/tests/test_web.py
dulwich/web.py

This doesn't have any unit tests; my manual tests show that this at least fixes cloning and pushing on Python 3.

Fix #295: Python 3 compatibility for dulwich.web

---

docs/tutorial/object-store.txt
dulwich/patch.py
dulwich/tests/test_patch.py
dulwich/tests/test_porcelain.py

@jelmer hello, 
Sorry, I messed up the previous PR, so I created the new one.
finally, tests are passing, and everything seems correct.

fix unified_diff implementation for issue #543

---

dulwich/object_store.py

https://github.com/jelmer/dulwich/issues/552
Signed-off-by:** Earl Chew <earl_chew@yahoo.com>

Take care not to remove consolidated pack after repacking

---

NEWS
dulwich/errors.py
dulwich/object_store.py
dulwich/objects.py
dulwich/tests/test_object_store.py

I still have implementation questions pending in the related issue.
I prefer opening the PR now to show the current state so that we can
discuss freely the implementation.
Related #582
(rebased as i was not up-to-date with upstream/master)

WIP - Raise exception when disk object corruption detected

---

dulwich/object_store.py

Simplify the existing solution for `DiskObjectStore._complete_thin_pack` and repeat it for `MemoryObjectStore.move_in_pack` that has the same need.
Checking the platform before unlinking was needed before since `WindowsError` was caught, which is only defined on Windows. Since this is a subclass of `OSError`, there is no real need to be that specific. The platform check can remain as a minor time saver, since it seems to be guaranteed that unlinking is never necessary on other platforms.
Another alternative could be using `shutil.move`, which silently replaces existing targets. Python 3.3 and newer also have `os.replace` for similar functionality.
The previous code comment mentioning that a possibly existing target file should have the same content as the source file seems to be false, …

More robust pack file rename on Windows

---

dulwich/line_ending.py
dulwich/tests/__init__.py
dulwich/tests/test_line_ending.py

This is an extract of https://github.com/dulwich/dulwich/pull/674#pullrequestreview-188184940 with only the conversion functions and associated tests.

Line ending convert support bases

---

dulwich/patch.py
dulwich/tests/compat/test_patch.py
dulwich/tests/test_patch.py
dulwich/tests/test_porcelain.py

The goal of this PR is to make dulwich generate diff compatible with `git apply`.

Update git diff format

---

.travis.yml

Build pure wheels on travis.

---

dulwich/repo.py
dulwich/tests/test_repository.py

Add new `_set_filesystem_hidden()` helper and use when creating controldirs. Only implement for win32 currently, which sets `FILE_ATTRIBUTE_HIDDEN` on the directory.
Fixes dulwich/dulwich#585

Hide .git control dirs on win32

---

dulwich/porcelain.py

This prefers to get the upstream defined from the config but it will
fallback to origin if none is found.
This should address TODO in https://github.com/dulwich/dulwich/commit/083dac6a727a26d5ae09b55d9acc7c573b738b98.
Related to #741

fix: Get branch remote from config

---

dulwich/hooks.py
dulwich/repo.py
dulwich/server.py

Similar to https://github.com/dulwich/dulwich/pull/214 , but for running post-receive scripts.
What needs to be done here?

post-receive hook

---

dulwich/repo.py

check for valid hexsha

---

.github/workflows/pythonpublish.yml

Adapted fix (https://github.com/pybamm-team/PyBaMM/pull/1198) for https://github.com/RalfG/python-wheels-manylinux-build/issues/26
Seems to work great in my tests https://github.com/efiop/dulwich/runs/1331771165?check_suite_focus=true

gha: fix linux wheel building for python 3.9

---

dulwich/tests/test_ignore.py

It is a demonstration of #836
However, I don't think I'll be able to fix it on my own.

Failing test for manpage gitignore example with IgnoreFilterManager

---

dulwich/reflog.py
dulwich/stash.py
dulwich/tests/test_reflog.py

* Implements `Stash.drop`
* Adds `drop_reflog_entry` method in `dulwich/reflog` for removing and rewriting reflog entries

stash: implement drop

---

NEWS
dulwich/client.py
dulwich/cloud/gcs.py
dulwich/object_store.py
dulwich/repo.py

Add a basic GcsObjectStore

---

.deepsource.toml
dulwich/cli.py
dulwich/client.py
dulwich/contrib/swift.py
dulwich/contrib/test_swift.py
dulwich/diff_tree.py
dulwich/greenthreads.py
dulwich/lru_cache.py
dulwich/protocol.py
dulwich/repo.py
dulwich/tests/compat/test_pack.py
dulwich/tests/compat/test_repository.py
dulwich/tests/test_pack.py
dulwich/tests/test_walk.py
setup.py

Hey :wave:, I'm a Developer Outreach at [DeepSource](https://deepsource.io/) and ran DeepSource analysis on my fork of the repo. It found some interesting [code quality improvements](https://deepsource.io/gh/akshgpt7/dulwich/) to consider.
This PR fixes a few of the issues detected for you to assess if it is right for you.
Happy to provide the tweaks separately otherwise :)
- Remove unnecessary generators.
- Remove unnecessary lambda expressions.
- Refactor the comparison involving `not`
- Remove calling `len()` for comparisons.
- Remove reimported modules.
- Add `.deepsource.toml` file for continuous analysis on bug risks/performance/code-quality issues on new changes.

chore: Refactor code quality issues

---

dulwich/ignore.py
dulwich/tests/test_ignore.py

Skip lines with spaces only in .gitignore

---

dulwich/file.py
dulwich/object_store.py
dulwich/tests/test_object_store.py
dulwich/tests/test_pack.py
dulwich/tests/test_repository.py
dulwich/tests/utils.py

adjust default file mask to be consistent with git

---

dulwich/objects.py

Fix assert format string

---

dulwich/tests/compat/test_client.py
dulwich/tests/compat/test_server.py
dulwich/tests/test_client.py
dulwich/tests/test_fastexport.py
dulwich/tests/test_file.py
dulwich/tests/test_lru_cache.py
dulwich/tests/test_missing_obj_finder.py
dulwich/tests/test_object_store.py
dulwich/tests/test_objects.py
dulwich/tests/test_pack.py
dulwich/tests/test_porcelain.py
dulwich/tests/test_refs.py
dulwich/tests/test_repository.py
dulwich/tests/test_server.py
dulwich/tests/test_utils.py
dulwich/tests/test_web.py

Improve assertions in Python unit tests.
This merge proposal was created automatically by the [Janitor bot](https://janitor.jelmer.uk/teyit).
For more information, including instructions on how to disable
these merge proposals, see https://janitor.jelmer.uk/teyit.
You can follow up to this merge proposal as you normally would.
The bot will automatically update the merge proposal to resolve merge conflicts
or close the merge proposal when all changes are applied through other means
(e.g. cherry-picks). Updates may take several hours to propagate.
Build and test logs for this branch can be found at
https://janitor.jelmer.uk/teyit/pkg/dulwich/cbf7ec4e-81f5-4acb-8c15-a2693440063b.

Improve assertions in Python unit tests

---

dulwich/contrib/test_paramiko_vendor.py

Skip paramiko tests if it is not installed.  This is based
on the skipping code found in dulwich/contrib/test_swift.py.

Skip paramiko tests if paramiko is not installed

---

dulwich/client.py
dulwich/tests/test_client.py

adds support for `file://` URLs on windows, according to https://datatracker.ietf.org/doc/html/rfc8089

client: add support for file:// urls on windows

---

NEWS
dulwich/client.py
dulwich/config.py
dulwich/tests/test_client.py

Support applying of URL rewriting using insteadOf/pushInsteadOf. 

---

dulwich/config.py

revisiting the type synonyms to bring more clarity, I found myself a little unhappy in the earlier MR with how this had ended up

better type synonyms

---

.flake8
.github/workflows/pythonpackage.yml
docs/conf.py
dulwich/repo.py
dulwich/tests/compat/test_porcelain.py
setup.py

Fix issues with newer flake8

---

Makefile
docs/conf.py
dulwich/client.py
dulwich/porcelain.py
dulwich/repo.py

Fix some pydoctor issues

---

.github/workflows/pythonpackage.yml
.github/workflows/pythonwheels.yml
CODE_OF_CONDUCT.md
SECURITY.md
status.yaml

Prettify md/yaml files

---

dulwich/config.py
dulwich/tests/test_config.py

Cope with closing bracket within quotes. Fixes #1014

Cope with closing bracket within quotes

---

setup.py

Drop distutils-only support, require setuptools.

Drop distutils-only support, require setuptools

---

dulwich/protocol.py

Explicitly handle ConnectionResetError.

Explicitly handle ConnectionResetError

---

NEWS
dulwich/tests/compat/test_client.py

Prepare for a release.
* Update NEWS
* Mark flaky test as known failing (for now)

Prepare for a release

---

NEWS
dulwich/__init__.py
setup.py

Import 0.20.46

---

.github/workflows/pythontest.yml

Trigger GitHub actions on PRs.

Trigger GitHub actions on PRs

---

dulwich/pack.py
dulwich/tests/test_pack.py

Refactoring Pack code to avoid circular references.
Add some typing.

Refactoring Pack code to avoid circular references

---

.github/workflows/docs.yml
Makefile
dulwich/porcelain.py

Fix docstring formatting

---

dulwich/pack.py

Move PackTupleIterable to top-level.

Move PackTupleIterable to top-level

---

dulwich/cli.py
dulwich/config.py
dulwich/porcelain.py
dulwich/tests/test_porcelain.py

Add basic support for "git submodule init"

Add basic support for "git submodule init"

---

NEWS
dulwich/config.py
dulwich/tests/test_config.py

Add another config test, for broken lines.

Add another config test, for broken lines

---

dulwich/server.py
dulwich/web.py

Some refactoring ahead of adding aiohttp support.

Some refactoring ahead of adding aiohttp support

---

dulwich/protocol.py
dulwich/server.py
dulwich/tests/test_server.py

Factor out some formatting functions ahead of aiohttp support.

Factor out some formatting functions ahead of aiohttp support

---

dulwich/protocol.py
dulwich/server.py

Factor out more formatting functions, ahead of asyncio support.

Factor out more formatting functions, ahead of asyncio support

---

dulwich/object_store.py
dulwich/pack.py
dulwich/tests/test_pack.py

Avoid copying data when creating deltas.

Avoid copying data when creating deltas

---

dulwich/pack.py

Use "yield from"

---

NEWS
dulwich/repo.py
dulwich/tests/test_repository.py

Support repository format version 1. Fixes #1056

Support repository format version 1

---

dulwich/client.py
dulwich/config.py
dulwich/contrib/swift.py
dulwich/file.py
dulwich/hooks.py
dulwich/lfs.py
dulwich/objects.py
dulwich/pack.py
dulwich/porcelain.py
dulwich/protocol.py
dulwich/repo.py
dulwich/server.py
dulwich/tests/test_fastexport.py
dulwich/tests/test_refs.py
dulwich/tests/utils.py
dulwich/walk.py

Use "raise from"

---

.github/workflows/releaser.yml

Validate releaesr configuration in GitHub actions.

Validate releaser configuration in GitHub actions

---

setup.cfg
setup.py

Move some metadata into setup.cfg.

Move some metadata into setup.cfg

---

setup.cfg
setup.py

Include some more metadata in setup.py

Include some more metadata in setup.cfg

---

dulwich/repo.py

inline getpass.getuser()
only call pwd.getpw*() once

inline getpass.getuser()

---

.github/workflows/pythonwheels.yml

Fix wheel artifact path

---

CONTRIBUTING.rst
disperse.conf
setup.cfg
setup.py

Use standard infrastructure to mark extensions as optional

Use standard infrastructure to mark extensions as optional

---

NEWS
dulwich/cli.py
dulwich/client.py
dulwich/porcelain.py

Add -b argument to "dulwich clone"

Add -b argument to "dulwich clone"

---

dulwich/index.py
dulwich/object_store.py
dulwich/porcelain.py
dulwich/repo.py

Add some more typing

---

NEWS
dulwich/credentials.py
dulwich/index.py
dulwich/tests/__init__.py
dulwich/tests/test_credentials.py
dulwich/tests/test_repository.py

Fix handling of removed files in Repo.reset_index

---

setup.cfg

Set the license_files tag

---

dulwich/porcelain.py
dulwich/tests/test_porcelain.py

This provides ability for user to request full commit through API

Allow passing abbrev to describe

---

setup.py

Fix --pure

---

dulwich/client.py

Cope with missing content type
Unfortunately our testing story for dumb remotes isn't great, so no updates there :-/

Cope with missing content type

---

dulwich/client.py
dulwich/tests/test_client.py

This implementation will honor a no_proxy environmental variable.
That will resolve the issue #932.

Implementation to honor no_proxy environment variable

---

dulwich/bundle.py
dulwich/client.py
dulwich/ignore.py
dulwich/index.py
dulwich/porcelain.py
dulwich/repo.py
dulwich/tests/compat/test_web.py
dulwich/tests/compat/utils.py
dulwich/tests/test_web.py
dulwich/web.py

Fix typing

---

.github/workflows/pythontest.yml
setup.cfg

Drop python 3.6

---

dulwich/cli.py
dulwich/objects.py

This pull request fixes a couple of issues I found while trying to test packfile generation with the 'dulwich pack-objects' command.

Fix pack objects cli

---

dulwich/config.py
dulwich/contrib/diffstat.py
dulwich/diff_tree.py
dulwich/errors.py
dulwich/graph.py
dulwich/lru_cache.py
dulwich/objects.py
dulwich/pack.py
dulwich/patch.py
dulwich/refs.py
setup.cfg

Add more typing

---

dulwich/pack.py

avoid refetching objects

---

dulwich/client.py
dulwich/fastexport.py
dulwich/greenthreads.py
dulwich/index.py
dulwich/line_ending.py
dulwich/object_store.py
dulwich/pack.py
dulwich/patch.py
dulwich/refs.py
dulwich/repo.py
dulwich/server.py
dulwich/submodule.py
dulwich/tests/test_object_store.py

Various bist of pack refactoring; add more typing.

Various bits of pack refactoring; add more typing

---

dulwich/object_store.py
dulwich/repo.py
dulwich/tests/test_missing_obj_finder.py

Factor out MissingObjectFinder

Factor out MissingObjectFinder

---

dulwich/client.py
dulwich/object_store.py
dulwich/pack.py

Various other pack fixes:
* avoid updating pack if unnecessary
* write more progress info

Various other pack fixes:

---

dulwich/object_store.py
dulwich/pack.py

Stop closing file in extend_pack + trivial fixes

Stop closing file in extend_pack + trivial fixes

---

docs/tutorial/remote.txt
dulwich/object_store.py
dulwich/tests/test_client.py
dulwich/tests/test_object_store.py
dulwich/tests/test_repository.py

Hopefully fix pack tests on Windows

Factor out common _complete_thin_pack

---

dulwich/object_store.py

Inline _move_in_pack - only used once.

Inline _move_in_pack - only used once

---

NEWS
dulwich/repo.py
dulwich/tests/test_repository.py

Add suport for worktreeconfig extension

Add suport for worktreeconfig extension

---

NEWS
dulwich/objects.py

Deprecate Commit.extra

---

.github/workflows/pythontest.yml

Please rerun the failing Windows test.  Perhaps is it a fluke.
> dulwich.errors.HangupException: The remote server unexpectedly closed the connection.

Upgrade GitHub Actions

---

dulwich/objects.py
dulwich/tests/test_objects.py

Use Commit._extra rather than deprecated Commit.extra

Use Commit._extra rather than deprecated Commit.extra

---

dulwich/tests/test_client.py

reformatted dulwich/tests/test_client.py
All done! 1 reformatted, 46 left unchanged

Use better assert function

---

NEWS
dulwich/objects.py

Goal is to make it possible to lazily parse time entry lines

Various bits of refactoring for dulwich.objects

---

.github/workflows/disperse.yml

Use disperse-validate action

---

dulwich/file.py

Warn when _GitFile is not closed

Warn when _GitFile is not closed

---

NEWS
dulwich/object_store.py
dulwich/tests/test_repository.py

Fix fetching into MemoryRepo
Fixes #1157

Fix fetching into MemoryRepo

---

dulwich/config.py
dulwich/errors.py
dulwich/ignore.py
dulwich/protocol.py
dulwich/refs.py
dulwich/tests/compat/test_client.py

Make sure GitProtocolError's first argument is a string

Make sure GitProtocolError's first argument is a string

---

NEWS
dulwich/objects.py
dulwich/pack.py
dulwich/tests/test_pack.py

FIx iterobjects_subset.
Fixes #1166

FIx iterobjects_subset

---

NEWS
dulwich/porcelain.py
dulwich/repo.py
dulwich/tests/test_repository.py

Support core.symlink=false

---

dulwich/protocol.py

Handle version tuples that are not three integers

Handle version tuples that are not three integers

---

dulwich/repo.py

Be backwards compatible with older derived Repo implementations

Be backwards compatible with older derived Repo implementations

---

dulwich/graph.py

Examined both original git merge logic and libgit2 merge logic and applied it to dulwich _find_lcas  to make it both
much more efficient and hopefully more robust to corner cases.

updates to the _find_lcas routine for improved efficiency and robustness

---

.codespellrc
.readthedocs.yml

Add the readthedocs configuration

Add the readthedocs configuration

---

dulwich/index.py
dulwich/tests/test_index.py

With these changes in place dulwich master passes make check.
Hope something close to this can be integrated into dulwich master so that work on an external merge capability can continue.

Make Index support multiple IndexEntries for the same path by stage for merge conflict support

---

dulwich/index.py
dulwich/tests/test_index.py

Define enum for stage values

---

NEWS
dulwich/client.py
dulwich/objects.py
dulwich/tests/test_client.py
dulwich/tests/test_repository.py

Raise GitProtocolError when encountering HTTP Errors in HTTPGitClient.

Raise GitProtocolError when encountering HTTP Errors in HTTPGitClient

---

NEWS
dulwich/client.py

Fix NameError when encountering errors during HTTP operation. Fixes #1208

Fix NameError when encountering errors during HTTP operation

---

NEWS
dulwich/repo.py

Raise exception when default identity can't be found.
See jelmer/xandikos#254

Raise exception when default identity can't be found

---

dulwich/client.py
dulwich/cloud/gcs.py
dulwich/graph.py
dulwich/ignore.py
dulwich/lru_cache.py
dulwich/patch.py
dulwich/tests/test_client.py
dulwich/tests/test_graph.py
dulwich/tests/test_walk.py
dulwich/walk.py
setup.py

Run pyupgrade

---

.github/workflows/python-distributions.yml

Upgrade cibuildwheel so python could build wheel
Close #1233

Update cibuildwheel in CI workflow

---

dulwich/client.py
dulwich/config.py
dulwich/contrib/requests_vendor.py
dulwich/contrib/swift.py
dulwich/contrib/test_release_robot.py
dulwich/contrib/test_swift.py
dulwich/contrib/test_swift_smoke.py
dulwich/fastexport.py
dulwich/hooks.py
dulwich/index.py
dulwich/pack.py
dulwich/porcelain.py
dulwich/protocol.py
dulwich/repo.py
dulwich/tests/__init__.py
dulwich/tests/compat/test_client.py
dulwich/tests/compat/test_pack.py
dulwich/tests/test_client.py
dulwich/tests/test_greenthreads.py
dulwich/tests/test_porcelain.py
dulwich/tests/test_repository.py
dulwich/tests/test_server.py
dulwich/tests/test_web.py
dulwich/tests/utils.py
dulwich/web.py
pyproject.toml

More ruff fixes

---

dulwich/client.py

Fix typing on pythn 3.7

---

NEWS
dulwich/__init__.py

Start on 0.21.8

---

pyproject.toml

https://github.com/pypa/trove-classifiers/blob/main/README.md

pyproject.toml: Add trove classifier for Python 3.12

---

NEWS
setup.py

Stop installing docs/ as part of package code

---

tests/test_greenthreads.py

Fix greenthreads import path in test_greenthreads.py

---

dulwich/contrib/swift.py

Fixes https://github.com/jelmer/dulwich/issues/1279

Keep up with changes in geventhttpclient

---

.github/workflows/pythontest.yml
pyproject.toml

Closes https://github.com/jelmer/dulwich/issues/1352

Support Python 3.13

---

tests/compat/test_client.py

Upgrade Python code to a modern version

Upgrade Python code to a modern version

---

dulwich/index.py

this fixes backwards compatibility

Add default values for IndexEntry

---

NEWS
dulwich/porcelain.py
tests/test_porcelain.py

Allow passing in plain strings to tag_create

---

.github/workflows/pythontest.yml
NEWS
dulwich/index.py
dulwich/merge.py
dulwich/porcelain.py
tests/__init__.py
tests/test_merge.py
tests/test_porcelain.py

Update working tree in pull

---

NEWS
dulwich/index.py
dulwich/repo.py
tests/compat/test_index.py
tests/test_index.py

Note that this just allows us to read these files - it does not implement path-prefix compression.
Fixes #1462

Add basic support for manyfiles feature

---

NEWS
dulwich/config.py
tests/test_config.py

Handle trailing backslashes in config files appropriately

---

NEWS
dulwich/object_store.py
tests/test_object_store.py
tests/test_repository.py

Fix LocalGitClient assertion error with MemoryRepo

---

NEWS
dulwich/cli.py
dulwich/gc.py
dulwich/object_store.py
dulwich/porcelain.py
dulwich/refs.py
dulwich/tests/test_cli.py
dulwich/tests/test_gc.py
dulwich/tests/test_object_store.py

Support garbage collection

---

NEWS
dulwich/client.py
dulwich/dumb.py
tests/compat/test_dumb.py
tests/compat/test_pack.py
tests/test_client.py
tests/test_dumb.py

Fix handling of fetching of packs over dumb http transports

---

NEWS
dulwich/server.py
tests/test_server.py

Fix TypeError when handling bytes paths in FileSystemBackend

---

NEWS
dulwich/cli.py
dulwich/client.py
dulwich/porcelain.py
tests/compat/test_client.py
tests/test_cli.py
tests/test_client.py
tests/test_porcelain.py

Return symrefs from ls_refs

---

NEWS
dulwich/gc.py
dulwich/object_store.py
dulwich/porcelain.py
dulwich/repo.py
tests/test_gc.py
tests/test_porcelain.py

... and invoke from some porcelain commands.
Fixes #1600

Add support for auto garbage collection.

---

NEWS
dulwich/__init__.py

Emit deprecation warnings on use rather than import

---

NEWS
dulwich/bundle.py
dulwich/client.py
tests/compat/__init__.py
tests/compat/test_bundle.py
tests/test_bundle.py
tests/test_client.py

* Add ``BundleClient`` for interacting with bundles like a Git client
* Add ``create_bundle_from_repo`` for easily creating bundles
Fixes #1246

Improve bundle handling

---

dulwich/client.py

Protov2 deepen

---

dulwich/attrs.py
dulwich/cli.py
dulwich/filters.py
dulwich/lfs.py
dulwich/lfs_server.py
dulwich/line_ending.py
dulwich/porcelain.py
dulwich/repo.py
tests/__init__.py
tests/compat/__init__.py
tests/compat/server_utils.py
tests/compat/test_commit_graph.py
tests/compat/test_lfs.py
tests/compat/test_reftable.py
tests/test_commit_graph.py
tests/test_filters.py
tests/test_grafts.py
tests/test_index.py
tests/test_lfs.py
tests/test_lfs_integration.py
tests/test_line_ending.py
tests/test_porcelain.py
tests/test_porcelain_filters.py
tests/test_porcelain_lfs.py
tests/test_porcelain_merge.py
tests/test_repository.py
tests/test_sparse_patterns.py

* Add compat tests for LFS
* Add porcelain for LFS
* Integrate with filters

Improve LFS support

---

dulwich/ignore.py
tests/compat/test_check_ignore.py
tests/test_ignore.py

Reduce complexity while maintaining exact Git-compatible behavior:
- Streamline _check_parent_exclusion function by combining conditions
- Consolidate _pattern_excludes_parent cases into cleaner flow
- Simplify Pattern.match method with more concise conditionals
- Remove redundant comments and intermediate variables
Fixes #1721

Simplify gitignore parent exclusion logic

---

NEWS
dulwich/cli.py
dulwich/porcelain.py
dulwich/repo.py
dulwich/worktree.py
tests/test_cli.py
tests/test_porcelain.py
tests/test_worktree.py

* Core functionality in dulwich/worktree.py:
* CLI support in dulwich/cli.py:
* Porcelain wrappers in dulwich/porcelain.py:
Fixes #1710, #1632

Implement basic worktree support

---

NEWS
dulwich/merge.py
tests/test_merge_drivers.py

Fix merge functionality to handle missing merge3 dependency gracefully

---

dulwich/merge.py

This seems to pass `mypy` checks just fine (version 1.17.1)

Factor out checks for merge3 module to a function

---

CONTRIBUTING.rst
dulwich/cli.py
tests/test_cli.py

Implements the --column flag for the dulwich branch command, 
which display branch list in columns.
https://github.com/jelmer/dulwich/issues/1847

add --column to branch command

---

dulwich/filters.py
tests/__init__.py
tests/test_filters.py

- Add missing test modules to tests/__init__.py:
* test_filter_branch
* test_filters
* test_lfs_integration
* test_whitespace
- Fix FilterContext

Fix test failures by adding missing test modules and fixing filter tests
